// Generated by scripts/generate-image-keys.mjs. Do not edit by hand.
//
// Every photograph the site draws from /images, and where it is drawn. This is
// to pictures what messages/en.json is to wording: the list of what a country
// site may replace with its own. Read by the Page wording collection, which
// offers these, and by components/ui/SiteImage, which swaps in whatever a
// country chose.
//
// Re-run `npm run generate-image-keys` after adding or removing an image.

export type SiteImage = {
  /** The path as the components write it, e.g. "/images/about-hero.webp". */
  path: string;
  /** The pages and components that draw it, for the label in the admin. */
  usedOn: string[];
};

export const SITE_IMAGES: SiteImage[] = [
  {
    "path": "/images/about-hero-banner.webp",
    "usedOn": [
      "AboutHero",
      "siteImages"
    ]
  },
  {
    "path": "/images/about-hero-cross.webp",
    "usedOn": [
      "/about",
      "siteImages"
    ]
  },
  {
    "path": "/images/about-mission-card.webp",
    "usedOn": [
      "/about",
      "/about/membership",
      "siteImages"
    ]
  },
  {
    "path": "/images/about-statement-faith-card.webp",
    "usedOn": [
      "/about",
      "/about/membership",
      "siteImages"
    ]
  },
  {
    "path": "/images/admin-intro-1.webp",
    "usedOn": [
      "/what-we-do/administration",
      "siteImages"
    ]
  },
  {
    "path": "/images/admin-intro-2.webp",
    "usedOn": [
      "/what-we-do/administration",
      "siteImages"
    ]
  },
  {
    "path": "/images/admin-intro-laptop.webp",
    "usedOn": [
      "/what-we-do/administration",
      "siteImages"
    ]
  },
  {
    "path": "/images/administration-hero.webp",
    "usedOn": [
      "/what-we-do/administration",
      "siteImages"
    ]
  },
  {
    "path": "/images/alumni-1.webp",
    "usedOn": [
      "/get-involved/alumni-connect",
      "siteImages"
    ]
  },
  {
    "path": "/images/alumni-2.webp",
    "usedOn": [
      "/get-involved/alumni-connect",
      "siteImages"
    ]
  },
  {
    "path": "/images/alumni-3.webp",
    "usedOn": [
      "/get-involved/alumni-connect",
      "siteImages"
    ]
  },
  {
    "path": "/images/alumni-hero.webp",
    "usedOn": [
      "/get-involved/alumni-connect",
      "siteImages"
    ]
  },
  {
    "path": "/images/bible-study-bible-core.webp",
    "usedOn": [
      "/bible-study",
      "siteImages"
    ]
  },
  {
    "path": "/images/bible-study-christian-life.webp",
    "usedOn": [
      "/bible-study",
      "siteImages"
    ]
  },
  {
    "path": "/images/bible-study-collage.webp",
    "usedOn": [
      "Newsletter",
      "siteImages"
    ]
  },
  {
    "path": "/images/bible-study-discipleship-track.webp",
    "usedOn": [
      "/bible-study",
      "siteImages"
    ]
  },
  {
    "path": "/images/bible-study-faith.webp",
    "usedOn": [
      "/bible-study",
      "siteImages"
    ]
  },
  {
    "path": "/images/bible-study-group.webp",
    "usedOn": [
      "BibleStudyProgram",
      "siteImages"
    ]
  },
  {
    "path": "/images/bible-study-hero.webp",
    "usedOn": [
      "/bible-study",
      "siteImages"
    ]
  },
  {
    "path": "/images/bible-study-join-hero.webp",
    "usedOn": [
      "/bible-study/join",
      "siteImages"
    ]
  },
  {
    "path": "/images/bible-study-only-jesus.webp",
    "usedOn": [
      "/bible-study",
      "siteImages"
    ]
  },
  {
    "path": "/images/bible-study-sola-fide.webp",
    "usedOn": [
      "/bible-study",
      "siteImages"
    ]
  },
  {
    "path": "/images/bible-teacher-called-to-be.webp",
    "usedOn": [
      "/get-involved/bible-teacher-training",
      "siteImages"
    ]
  },
  {
    "path": "/images/bible-teacher-called-to-serve.webp",
    "usedOn": [
      "/get-involved/bible-teacher-training",
      "siteImages"
    ]
  },
  {
    "path": "/images/bible-teacher-hero.webp",
    "usedOn": [
      "/get-involved/bible-teacher-training",
      "siteImages"
    ]
  },
  {
    "path": "/images/chairman-photo-1.webp",
    "usedOn": [
      "/about/chairman",
      "siteImages"
    ]
  },
  {
    "path": "/images/chairman-photo-2.webp",
    "usedOn": [
      "/about/chairman",
      "siteImages"
    ]
  },
  {
    "path": "/images/chapter-affiliation-hero.webp",
    "usedOn": [
      "/get-involved/chapter-affiliation",
      "siteImages"
    ]
  },
  {
    "path": "/images/chapter-volunteer-1.webp",
    "usedOn": [
      "/get-involved/chapter-staff",
      "siteImages"
    ]
  },
  {
    "path": "/images/chapter-volunteer-2.webp",
    "usedOn": [
      "/get-involved/chapter-staff",
      "siteImages"
    ]
  },
  {
    "path": "/images/chapter-volunteer-3.webp",
    "usedOn": [
      "/get-involved/chapter-staff",
      "siteImages"
    ]
  },
  {
    "path": "/images/chapter-volunteer-group.webp",
    "usedOn": [
      "/get-involved/chapter-staff",
      "siteImages"
    ]
  },
  {
    "path": "/images/contact-hero.webp",
    "usedOn": [
      "/contact",
      "siteImages"
    ]
  },
  {
    "path": "/images/coord-andrea-rico.webp",
    "usedOn": [
      "/about/leadership",
      "siteImages"
    ]
  },
  {
    "path": "/images/coord-joel-lee.webp",
    "usedOn": [
      "/about/leadership",
      "siteImages"
    ]
  },
  {
    "path": "/images/coord-jonathan-xie.webp",
    "usedOn": [
      "/about/leadership",
      "siteImages"
    ]
  },
  {
    "path": "/images/coord-khiaghie-koropa.webp",
    "usedOn": [
      "/about/leadership",
      "siteImages"
    ]
  },
  {
    "path": "/images/coord-mara-onyeama.webp",
    "usedOn": [
      "/about/leadership",
      "siteImages"
    ]
  },
  {
    "path": "/images/coord-priya-vaya.webp",
    "usedOn": [
      "/about/leadership",
      "siteImages"
    ]
  },
  {
    "path": "/images/coord-samuel-kwizera.webp",
    "usedOn": [
      "/about/leadership",
      "siteImages"
    ]
  },
  {
    "path": "/images/donate-hero.webp",
    "usedOn": [
      "/get-involved/donate",
      "/get-involved/donate/thank-you",
      "siteImages"
    ]
  },
  {
    "path": "/images/donate-offering.webp",
    "usedOn": [
      "/get-involved/donate",
      "siteImages"
    ]
  },
  {
    "path": "/images/events-hero.webp",
    "usedOn": [
      "/events",
      "siteImages"
    ]
  },
  {
    "path": "/images/get-involved-bible-studies.webp",
    "usedOn": [
      "GetInvolved",
      "siteImages"
    ]
  },
  {
    "path": "/images/get-involved-connect.webp",
    "usedOn": [
      "/get-involved",
      "siteImages"
    ]
  },
  {
    "path": "/images/get-involved-grow.webp",
    "usedOn": [
      "/get-involved",
      "siteImages"
    ]
  },
  {
    "path": "/images/get-involved-hero.webp",
    "usedOn": [
      "GetInvolvedHero",
      "siteImages"
    ]
  },
  {
    "path": "/images/get-involved-internship.webp",
    "usedOn": [
      "GetInvolved",
      "siteImages"
    ]
  },
  {
    "path": "/images/get-involved-lead.webp",
    "usedOn": [
      "/get-involved",
      "siteImages"
    ]
  },
  {
    "path": "/images/get-involved-sent.webp",
    "usedOn": [
      "/get-involved",
      "siteImages"
    ]
  },
  {
    "path": "/images/get-involved-volunteer.webp",
    "usedOn": [
      "GetInvolved",
      "siteImages"
    ]
  },
  {
    "path": "/images/group-activities-bible-study.webp",
    "usedOn": [
      "/get-involved/group-activities",
      "siteImages"
    ]
  },
  {
    "path": "/images/group-activities-fellowship.webp",
    "usedOn": [
      "/get-involved/group-activities",
      "siteImages"
    ]
  },
  {
    "path": "/images/group-activities-hero.webp",
    "usedOn": [
      "/get-involved/group-activities",
      "siteImages"
    ]
  },
  {
    "path": "/images/group-activities-morning-qt.webp",
    "usedOn": [
      "/get-involved/group-activities",
      "siteImages"
    ]
  },
  {
    "path": "/images/group-activities-prayer.webp",
    "usedOn": [
      "/get-involved/group-activities",
      "siteImages"
    ]
  },
  {
    "path": "/images/group-activities-weekend-1.webp",
    "usedOn": [
      "/get-involved/group-activities",
      "siteImages"
    ]
  },
  {
    "path": "/images/group-activities-weekend-2.webp",
    "usedOn": [
      "/get-involved/group-activities",
      "siteImages"
    ]
  },
  {
    "path": "/images/group-activities-weekend-3.webp",
    "usedOn": [
      "/get-involved/group-activities",
      "siteImages"
    ]
  },
  {
    "path": "/images/group-activities-weekend-4.webp",
    "usedOn": [
      "/get-involved/group-activities",
      "siteImages"
    ]
  },
  {
    "path": "/images/hero-purple-sky.webp",
    "usedOn": [
      "/get-involved/chapter-staff",
      "siteImages"
    ]
  },
  {
    "path": "/images/hero-slide-bible-study.webp",
    "usedOn": [
      "Hero",
      "siteImages"
    ]
  },
  {
    "path": "/images/hero-slide-campus.webp",
    "usedOn": [
      "Hero",
      "siteImages"
    ]
  },
  {
    "path": "/images/history-hero.webp",
    "usedOn": [
      "/about/history",
      "siteImages"
    ]
  },
  {
    "path": "/images/honorary-chairman.webp",
    "usedOn": [
      "HonoraryChairman",
      "siteImages"
    ]
  },
  {
    "path": "/images/hq-asa-daboh.webp",
    "usedOn": [
      "/about/leadership",
      "siteImages"
    ]
  },
  {
    "path": "/images/hq-can-liu.webp",
    "usedOn": [
      "/about/leadership",
      "siteImages"
    ]
  },
  {
    "path": "/images/hq-ruth-jigmedsuren.webp",
    "usedOn": [
      "/about/leadership",
      "siteImages"
    ]
  },
  {
    "path": "/images/internship-1.webp",
    "usedOn": [
      "/get-involved/internship",
      "siteImages"
    ]
  },
  {
    "path": "/images/internship-2.webp",
    "usedOn": [
      "/get-involved/internship",
      "siteImages"
    ]
  },
  {
    "path": "/images/internship-3.webp",
    "usedOn": [
      "/get-involved/internship",
      "siteImages"
    ]
  },
  {
    "path": "/images/internship-hero.webp",
    "usedOn": [
      "/get-involved/internship",
      "siteImages"
    ]
  },
  {
    "path": "/images/leader-paul-devries.webp",
    "usedOn": [
      "/about/leadership",
      "siteImages"
    ]
  },
  {
    "path": "/images/leader-reid.webp",
    "usedOn": [
      "/about/leadership",
      "siteImages"
    ]
  },
  {
    "path": "/images/media-video-poster.webp",
    "usedOn": [
      "Media",
      "siteImages"
    ]
  },
  {
    "path": "/images/membership-hero.webp",
    "usedOn": [
      "/about/membership",
      "siteImages"
    ]
  },
  {
    "path": "/images/ministry-connect.webp",
    "usedOn": [
      "Ministries",
      "siteImages"
    ]
  },
  {
    "path": "/images/ministry-grow.webp",
    "usedOn": [
      "Ministries",
      "siteImages"
    ]
  },
  {
    "path": "/images/ministry-lead.webp",
    "usedOn": [
      "Ministries",
      "siteImages"
    ]
  },
  {
    "path": "/images/mission-hero.webp",
    "usedOn": [
      "/about/mission",
      "siteImages"
    ]
  },
  {
    "path": "/images/network-continent-hero.webp",
    "usedOn": [
      "/network/[continent]",
      "siteImages"
    ]
  },
  {
    "path": "/images/news-hero.webp",
    "usedOn": [
      "NewsListPage",
      "siteImages"
    ]
  },
  {
    "path": "/images/online-bible-study-1.webp",
    "usedOn": [
      "/get-involved/online-bible-study",
      "siteImages"
    ]
  },
  {
    "path": "/images/online-bible-study-2.webp",
    "usedOn": [
      "/get-involved/online-bible-study",
      "siteImages"
    ]
  },
  {
    "path": "/images/online-bible-study-3.webp",
    "usedOn": [
      "/get-involved/online-bible-study",
      "siteImages"
    ]
  },
  {
    "path": "/images/online-bible-study-hero.webp",
    "usedOn": [
      "/get-involved/online-bible-study",
      "siteImages"
    ]
  },
  {
    "path": "/images/pillars-discipleship.webp",
    "usedOn": [
      "/what-we-do/pillars-of-mission",
      "siteImages"
    ]
  },
  {
    "path": "/images/pillars-education.webp",
    "usedOn": [
      "/what-we-do/pillars-of-mission",
      "siteImages"
    ]
  },
  {
    "path": "/images/pillars-evangelism.webp",
    "usedOn": [
      "/what-we-do/pillars-of-mission",
      "siteImages"
    ]
  },
  {
    "path": "/images/pillars-hero.webp",
    "usedOn": [
      "PillarsHero",
      "siteImages"
    ]
  },
  {
    "path": "/images/pillars-intro-1.webp",
    "usedOn": [
      "/what-we-do/pillars-of-mission",
      "siteImages"
    ]
  },
  {
    "path": "/images/pillars-mission.webp",
    "usedOn": [
      "/what-we-do/pillars-of-mission",
      "siteImages"
    ]
  },
  {
    "path": "/images/statement-of-faith-hero.webp",
    "usedOn": [
      "/about/statement-of-faith",
      "siteImages"
    ]
  },
  {
    "path": "/images/volunteer-calling.webp",
    "usedOn": [
      "/get-involved/volunteer",
      "siteImages"
    ]
  },
  {
    "path": "/images/volunteer-hero.webp",
    "usedOn": [
      "/get-involved/volunteer",
      "siteImages"
    ]
  },
  {
    "path": "/images/volunteer-team.webp",
    "usedOn": [
      "/get-involved/volunteer",
      "siteImages"
    ]
  },
  {
    "path": "/images/volunteer-worship.webp",
    "usedOn": [
      "/get-involved/volunteer",
      "siteImages"
    ]
  }
];

/** Reverse lookup, for resolving a path at render time. */
export const SITE_IMAGE_PATHS: ReadonlySet<string> = new Set(
  SITE_IMAGES.map((image) => image.path),
);
