-- Generated by scripts/generate-catchup-sql.mjs. Do not hand-edit; regenerate.
-- 2026-09-06
--
-- 2 table(s), 15 column(s) on 14 existing table(s), 23 type(s), 0 value(s) on 0 existing type(s).
--
-- Additive only: no DROP, no change to an existing column, and the only
-- ALTER TYPE is ADD VALUE, which takes nothing away from an enum.
-- Every statement is safe to run twice.


BEGIN;

-- 23 new type(s).

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_accordion_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_banner_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cards_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cards_layout AS ENUM ('card', 'ruled');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cta_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_embed_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_gallery_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_image_text_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_logos_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_people_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_prose_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_quote_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_spacer_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_stats_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_steps_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_timeline_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_timeline_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_timeline_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_timeline_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_timeline_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_timeline_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_timeline_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_timeline_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

-- 2 new table(s), with their types, keys and indexes.

CREATE TABLE IF NOT EXISTS public.pages_blocks_timeline (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    appearance_background public.enum_pages_blocks_timeline_appearance_background DEFAULT 'default'::public.enum_pages_blocks_timeline_appearance_background,
    appearance_text_theme public.enum_pages_blocks_timeline_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_timeline_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_timeline_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_timeline_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_timeline_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_timeline_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_timeline_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_timeline_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_timeline_appearance_width DEFAULT 'default'::public.enum_pages_blocks_timeline_appearance_width,
    appearance_align public.enum_pages_blocks_timeline_appearance_align DEFAULT 'default'::public.enum_pages_blocks_timeline_appearance_align,
    appearance_heading_size public.enum_pages_blocks_timeline_appearance_heading_size DEFAULT 'default'::public.enum_pages_blocks_timeline_appearance_heading_size,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_timeline_milestones (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    tag character varying NOT NULL,
    title character varying NOT NULL,
    description character varying
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_timeline_milestones_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_timeline_milestones ADD CONSTRAINT pages_blocks_timeline_milestones_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_timeline_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_timeline ADD CONSTRAINT pages_blocks_timeline_pkey PRIMARY KEY (id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS pages_blocks_timeline_appearance_appearance_background_i_idx ON public.pages_blocks_timeline USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_timeline_milestones_order_idx ON public.pages_blocks_timeline_milestones USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_timeline_milestones_parent_id_idx ON public.pages_blocks_timeline_milestones USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_timeline_order_idx ON public.pages_blocks_timeline USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_timeline_parent_id_idx ON public.pages_blocks_timeline USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_timeline_path_idx ON public.pages_blocks_timeline USING btree (_path);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_timeline_appearance_background_image_id_media_id_f' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_timeline ADD CONSTRAINT pages_blocks_timeline_appearance_background_image_id_media_id_f FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_timeline_milestones_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_timeline_milestones ADD CONSTRAINT pages_blocks_timeline_milestones_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages_blocks_timeline(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_timeline_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_timeline ADD CONSTRAINT pages_blocks_timeline_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

-- New columns on 14 existing table(s).

ALTER TABLE public.pages_blocks_steps ADD COLUMN IF NOT EXISTS appearance_heading_size enum_pages_blocks_steps_appearance_heading_size DEFAULT 'default'::enum_pages_blocks_steps_appearance_heading_size;

ALTER TABLE public.pages_blocks_stats ADD COLUMN IF NOT EXISTS appearance_heading_size enum_pages_blocks_stats_appearance_heading_size DEFAULT 'default'::enum_pages_blocks_stats_appearance_heading_size;

ALTER TABLE public.pages_blocks_cards ADD COLUMN IF NOT EXISTS layout enum_pages_blocks_cards_layout DEFAULT 'card'::enum_pages_blocks_cards_layout;
ALTER TABLE public.pages_blocks_cards ADD COLUMN IF NOT EXISTS appearance_heading_size enum_pages_blocks_cards_appearance_heading_size DEFAULT 'default'::enum_pages_blocks_cards_appearance_heading_size;

ALTER TABLE public.pages_blocks_people ADD COLUMN IF NOT EXISTS appearance_heading_size enum_pages_blocks_people_appearance_heading_size DEFAULT 'default'::enum_pages_blocks_people_appearance_heading_size;

ALTER TABLE public.pages_blocks_image_text ADD COLUMN IF NOT EXISTS appearance_heading_size enum_pages_blocks_image_text_appearance_heading_size DEFAULT 'default'::enum_pages_blocks_image_text_appearance_heading_size;

ALTER TABLE public.pages_blocks_cta ADD COLUMN IF NOT EXISTS appearance_heading_size enum_pages_blocks_cta_appearance_heading_size DEFAULT 'default'::enum_pages_blocks_cta_appearance_heading_size;

ALTER TABLE public.pages_blocks_gallery ADD COLUMN IF NOT EXISTS appearance_heading_size enum_pages_blocks_gallery_appearance_heading_size DEFAULT 'default'::enum_pages_blocks_gallery_appearance_heading_size;

ALTER TABLE public.pages_blocks_embed ADD COLUMN IF NOT EXISTS appearance_heading_size enum_pages_blocks_embed_appearance_heading_size DEFAULT 'default'::enum_pages_blocks_embed_appearance_heading_size;

ALTER TABLE public.pages_blocks_quote ADD COLUMN IF NOT EXISTS appearance_heading_size enum_pages_blocks_quote_appearance_heading_size DEFAULT 'default'::enum_pages_blocks_quote_appearance_heading_size;

ALTER TABLE public.pages_blocks_logos ADD COLUMN IF NOT EXISTS appearance_heading_size enum_pages_blocks_logos_appearance_heading_size DEFAULT 'default'::enum_pages_blocks_logos_appearance_heading_size;

ALTER TABLE public.pages_blocks_prose ADD COLUMN IF NOT EXISTS appearance_heading_size enum_pages_blocks_prose_appearance_heading_size DEFAULT 'default'::enum_pages_blocks_prose_appearance_heading_size;

ALTER TABLE public.pages_blocks_accordion ADD COLUMN IF NOT EXISTS appearance_heading_size enum_pages_blocks_accordion_appearance_heading_size DEFAULT 'default'::enum_pages_blocks_accordion_appearance_heading_size;

ALTER TABLE public.pages_blocks_banner ADD COLUMN IF NOT EXISTS appearance_heading_size enum_pages_blocks_banner_appearance_heading_size DEFAULT 'default'::enum_pages_blocks_banner_appearance_heading_size;

ALTER TABLE public.pages_blocks_spacer ADD COLUMN IF NOT EXISTS appearance_heading_size enum_pages_blocks_spacer_appearance_heading_size DEFAULT 'default'::enum_pages_blocks_spacer_appearance_heading_size;

COMMIT;

