-- Generated by scripts/generate-catchup-sql.mjs. Do not hand-edit; regenerate.
-- 2026-09-06
--
-- 0 table(s), 2 column(s) on 2 existing table(s), 2 type(s), 0 value(s) on 0 existing type(s).
--
-- Additive only: no DROP, no change to an existing column, and the only
-- ALTER TYPE is ADD VALUE, which takes nothing away from an enum.
-- Every statement is safe to run twice.


BEGIN;

-- 2 new type(s).

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cards_cards_icon AS ENUM ('', 'heart', 'book', 'monitor', 'palette', 'people', 'pin', 'calendar', 'newspaper', 'graduation', 'gift');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_prose_layout AS ENUM ('stacked', 'aside');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

-- New columns on 2 existing table(s).

ALTER TABLE public.pages_blocks_prose ADD COLUMN IF NOT EXISTS layout enum_pages_blocks_prose_layout DEFAULT 'stacked'::enum_pages_blocks_prose_layout;

ALTER TABLE public.pages_blocks_cards_cards ADD COLUMN IF NOT EXISTS icon enum_pages_blocks_cards_cards_icon;

COMMIT;

