-- The rotating slides behind the homepage headline, editable in the admin.
--
-- The Hero block held one background image and one headline, so authoring it
-- collapsed the carousel to a single slide. It now holds a list of slides —
-- picture, and two lines of headline — which is a table of its own.
--
-- Needed because `push` is development-only: a field added to a block reaches
-- a local database by itself and never the deployed one, and until it does,
-- every query that selects it fails — which takes out the whole Pages
-- collection, not just the new field. See scripts/README.md.
--
-- Not hand-written. Generated by pushing the schema into a throwaway database
-- and reading the table back, so this is the shape Payload's Postgres adapter
-- expects.
--
-- Safe to run more than once. Adds only; drops nothing.

CREATE TABLE IF NOT EXISTS "public"."pages_blocks_hero_slides" (
  "_order" integer NOT NULL,
  "_parent_id" varchar NOT NULL,
  "id" varchar PRIMARY KEY,
  "image_id" integer,
  "line1" varchar,
  "line2" varchar
);

DO $$ BEGIN
  ALTER TABLE "public"."pages_blocks_hero_slides"
    ADD CONSTRAINT "pages_blocks_hero_slides_parent_id_fk"
    FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_hero"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "public"."pages_blocks_hero_slides"
    ADD CONSTRAINT "pages_blocks_hero_slides_image_id_media_id_fk"
    FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "pages_blocks_hero_slides_order_idx"
  ON "public"."pages_blocks_hero_slides" USING btree ("_order");
CREATE INDEX IF NOT EXISTS "pages_blocks_hero_slides_parent_id_idx"
  ON "public"."pages_blocks_hero_slides" USING btree ("_parent_id");
CREATE INDEX IF NOT EXISTS "pages_blocks_hero_slides_image_idx"
  ON "public"."pages_blocks_hero_slides" USING btree ("image_id");
