-- The three account levels: super admin, admin, sub admin.
--
-- Super admin runs the network. An admin is given continents, countries, or
-- both, and reaches every country site inside them — a country added to that
-- continent later needs no further granting. A sub admin reaches only the
-- countries named on it, which is exactly what the old "country admin" was, so
-- existing accounts keep working under the old name and are read as sub
-- admins. Rename them at leisure with the UPDATE at the foot of this file.
--
-- Needed because `push` is development-only: a role added to a collection
-- reaches a local database by itself and never the deployed one, and until it
-- does, saving an account with the new role fails with 'invalid input value
-- for enum'. See scripts/README.md.
--
-- Not hand-written. Generated by pushing the schema into a throwaway database
-- and reading the tables back, so this is the shape Payload's Postgres adapter
-- expects.
--
-- Safe to run more than once. Adds only; drops nothing.
--
-- Deliberately not wrapped in a transaction: ADD VALUE and using the value
-- cannot share one.

ALTER TYPE "public"."enum_users_role" ADD VALUE IF NOT EXISTS 'admin';
ALTER TYPE "public"."enum_users_role" ADD VALUE IF NOT EXISTS 'sub-admin';

DO $$ BEGIN
  CREATE TYPE "public"."enum_users_continents" AS ENUM (
    'africa', 'asia', 'europe', 'northamerica', 'southamerica', 'oceania'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "public"."users_continents" (
  "order" integer NOT NULL,
  "parent_id" integer NOT NULL,
  "value" "public"."enum_users_continents",
  "id" serial PRIMARY KEY
);

DO $$ BEGIN
  ALTER TABLE "public"."users_continents"
    ADD CONSTRAINT "users_continents_parent_fk"
    FOREIGN KEY ("parent_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "users_continents_order_idx"
  ON "public"."users_continents" USING btree ("order");
CREATE INDEX IF NOT EXISTS "users_continents_parent_idx"
  ON "public"."users_continents" USING btree ("parent_id");

-- Optional, and only once the two statements above have been committed: give
-- the old accounts the name that now describes them. Nothing depends on it —
-- "country-admin" is read as a sub admin either way — so run it when you like.
--
--   UPDATE "public"."users" SET "role" = 'sub-admin' WHERE "role" = 'country-admin';
