-- Generated by scripts/generate-catchup-sql.mjs. Do not hand-edit; regenerate.
-- 2026-09-05
--
-- 4 table(s), 1 column(s) on 1 existing table(s), 0 type(s), 1 value(s) on 1 existing type(s).
--
-- Additive only: no DROP, no change to an existing column, and the only
-- ALTER TYPE is ADD VALUE, which takes nothing away from an enum.
-- Every statement is safe to run twice.


-- 1 new value(s) on existing types.

ALTER TYPE public.enum_users_sections ADD VALUE IF NOT EXISTS 'leaders' BEFORE 'tenant-content';

BEGIN;

-- 4 new table(s), with their types, keys and indexes.

CREATE TABLE IF NOT EXISTS public.leaders (
    id integer NOT NULL,
    name character varying NOT NULL,
    tenant_id integer NOT NULL,
    photo_id integer,
    fellowship_affiliation character varying,
    membership_status public.enum_leaders_membership_status,
    evangelism_date timestamp(3) with time zone,
    evangelism_pathway character varying,
    evangelised_by character varying,
    discipled_by character varying,
    mentor character varying,
    faith_and_order_status public.enum_leaders_faith_and_order_status,
    current_position character varying,
    next_stage character varying,
    required_qualifications character varying,
    recommendations character varying,
    affiliated_center character varying,
    center_address character varying,
    country_website character varying,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.leaders_documents (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id character varying NOT NULL,
    title character varying NOT NULL,
    file_id integer NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS public.leaders_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

DO $$
BEGIN
  ALTER SEQUENCE public.leaders_id_seq OWNED BY public.leaders.id;
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.leaders_previous_positions (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id character varying NOT NULL,
    "position" character varying NOT NULL,
    "from" timestamp(3) with time zone,
    "to" timestamp(3) with time zone
);

CREATE TABLE IF NOT EXISTS public.leaders_training (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id character varying NOT NULL,
    name character varying NOT NULL,
    completed_on timestamp(3) with time zone
);

DO $$
BEGIN
  ALTER TABLE ONLY public.leaders ALTER COLUMN id SET DEFAULT nextval('public.leaders_id_seq'::regclass);
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'leaders_documents_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.leaders_documents ADD CONSTRAINT leaders_documents_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'leaders_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.leaders ADD CONSTRAINT leaders_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'leaders_previous_positions_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.leaders_previous_positions ADD CONSTRAINT leaders_previous_positions_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'leaders_training_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.leaders_training ADD CONSTRAINT leaders_training_pkey PRIMARY KEY (id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS leaders_created_at_idx ON public.leaders USING btree (created_at);

CREATE INDEX IF NOT EXISTS leaders_documents_file_idx ON public.leaders_documents USING btree (file_id);

CREATE INDEX IF NOT EXISTS leaders_documents_order_idx ON public.leaders_documents USING btree (_order);

CREATE INDEX IF NOT EXISTS leaders_documents_parent_id_idx ON public.leaders_documents USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS leaders_photo_idx ON public.leaders USING btree (photo_id);

CREATE INDEX IF NOT EXISTS leaders_previous_positions_order_idx ON public.leaders_previous_positions USING btree (_order);

CREATE INDEX IF NOT EXISTS leaders_previous_positions_parent_id_idx ON public.leaders_previous_positions USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS leaders_tenant_idx ON public.leaders USING btree (tenant_id);

CREATE INDEX IF NOT EXISTS leaders_training_order_idx ON public.leaders_training USING btree (_order);

CREATE INDEX IF NOT EXISTS leaders_training_parent_id_idx ON public.leaders_training USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS leaders_updated_at_idx ON public.leaders USING btree (updated_at);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'leaders_documents_file_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.leaders_documents ADD CONSTRAINT leaders_documents_file_id_media_id_fk FOREIGN KEY (file_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'leaders_documents_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.leaders_documents ADD CONSTRAINT leaders_documents_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.leaders(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'leaders_photo_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.leaders ADD CONSTRAINT leaders_photo_id_media_id_fk FOREIGN KEY (photo_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'leaders_previous_positions_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.leaders_previous_positions ADD CONSTRAINT leaders_previous_positions_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.leaders(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'leaders_tenant_id_tenants_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.leaders ADD CONSTRAINT leaders_tenant_id_tenants_id_fk FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'leaders_training_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.leaders_training ADD CONSTRAINT leaders_training_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.leaders(id) ON DELETE CASCADE;
  END IF;
END $$;

-- New columns on 1 existing table(s).

ALTER TABLE public.payload_locked_documents_rels ADD COLUMN IF NOT EXISTS leaders_id integer;

-- 1 index(es) for those columns.

CREATE INDEX IF NOT EXISTS payload_locked_documents_rels_leaders_id_idx ON public.payload_locked_documents_rels USING btree (leaders_id);

COMMIT;

