-- Generated by scripts/generate-catchup-sql.mjs. Do not hand-edit; regenerate.
-- 2026-09-14
--
-- 3 table(s), 0 column(s) on 0 existing table(s), 8 type(s), 0 value(s) on 0 existing type(s).
--
-- Additive only: no DROP, no change to an existing column, and the only
-- ALTER TYPE is ADD VALUE, which takes nothing away from an enum.
-- Every statement is safe to run twice.


BEGIN;

-- 8 type(s), created if they are not already there.

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_campus_tour_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_campus_tour_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_campus_tour_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_campus_tour_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_campus_tour_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_campus_tour_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_campus_tour_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_campus_tour_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

-- 3 new table(s), with their types, keys and indexes.

CREATE TABLE IF NOT EXISTS public.pages_blocks_campus_tour (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    hint character varying,
    aerial_id integer,
    appearance_background public.enum_pages_blocks_campus_tour_appearance_background DEFAULT 'default'::public.enum_pages_blocks_campus_tour_appearance_background,
    appearance_text_theme public.enum_pages_blocks_campus_tour_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_campus_tour_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_campus_tour_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_campus_tour_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_campus_tour_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_campus_tour_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_campus_tour_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_campus_tour_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_campus_tour_appearance_width DEFAULT 'default'::public.enum_pages_blocks_campus_tour_appearance_width,
    appearance_align public.enum_pages_blocks_campus_tour_appearance_align DEFAULT 'default'::public.enum_pages_blocks_campus_tour_appearance_align,
    appearance_heading_size public.enum_pages_blocks_campus_tour_appearance_heading_size DEFAULT 'default'::public.enum_pages_blocks_campus_tour_appearance_heading_size,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_campus_tour_buildings (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    name character varying NOT NULL,
    tag character varying,
    text character varying,
    photo_id integer,
    shape character varying,
    pin_left numeric,
    pin_top numeric,
    leader_x1 numeric,
    leader_y1 numeric,
    leader_x2 numeric,
    leader_y2 numeric
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_campus_tour_buildings_gallery (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    image_id integer,
    caption character varying
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_campus_tour_buildings_gallery_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_campus_tour_buildings_gallery ADD CONSTRAINT pages_blocks_campus_tour_buildings_gallery_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_campus_tour_buildings_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_campus_tour_buildings ADD CONSTRAINT pages_blocks_campus_tour_buildings_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_campus_tour_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_campus_tour ADD CONSTRAINT pages_blocks_campus_tour_pkey PRIMARY KEY (id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS pages_blocks_campus_tour_aerial_idx ON public.pages_blocks_campus_tour USING btree (aerial_id);

CREATE INDEX IF NOT EXISTS pages_blocks_campus_tour_appearance_appearance_backgroun_idx ON public.pages_blocks_campus_tour USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_campus_tour_buildings_gallery_image_idx ON public.pages_blocks_campus_tour_buildings_gallery USING btree (image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_campus_tour_buildings_gallery_order_idx ON public.pages_blocks_campus_tour_buildings_gallery USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_campus_tour_buildings_gallery_parent_id_idx ON public.pages_blocks_campus_tour_buildings_gallery USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_campus_tour_buildings_order_idx ON public.pages_blocks_campus_tour_buildings USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_campus_tour_buildings_parent_id_idx ON public.pages_blocks_campus_tour_buildings USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_campus_tour_buildings_photo_idx ON public.pages_blocks_campus_tour_buildings USING btree (photo_id);

CREATE INDEX IF NOT EXISTS pages_blocks_campus_tour_order_idx ON public.pages_blocks_campus_tour USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_campus_tour_parent_id_idx ON public.pages_blocks_campus_tour USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_campus_tour_path_idx ON public.pages_blocks_campus_tour USING btree (_path);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_campus_tour_aerial_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_campus_tour ADD CONSTRAINT pages_blocks_campus_tour_aerial_id_media_id_fk FOREIGN KEY (aerial_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_campus_tour_appearance_background_image_id_media_i' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_campus_tour ADD CONSTRAINT pages_blocks_campus_tour_appearance_background_image_id_media_i FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_campus_tour_buildings_gallery_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_campus_tour_buildings_gallery ADD CONSTRAINT pages_blocks_campus_tour_buildings_gallery_image_id_media_id_fk FOREIGN KEY (image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_campus_tour_buildings_gallery_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_campus_tour_buildings_gallery ADD CONSTRAINT pages_blocks_campus_tour_buildings_gallery_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages_blocks_campus_tour_buildings(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_campus_tour_buildings_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_campus_tour_buildings ADD CONSTRAINT pages_blocks_campus_tour_buildings_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages_blocks_campus_tour(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_campus_tour_buildings_photo_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_campus_tour_buildings ADD CONSTRAINT pages_blocks_campus_tour_buildings_photo_id_media_id_fk FOREIGN KEY (photo_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_campus_tour_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_campus_tour ADD CONSTRAINT pages_blocks_campus_tour_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

COMMIT;

