-- Generated by scripts/generate-catchup-sql.mjs. Do not hand-edit; regenerate.
-- 2026-09-06
--
-- 1 table(s), 1 column(s) on 1 existing table(s), 10 type(s), 3 value(s) on 3 existing type(s).
--
-- Additive only: no DROP, no change to an existing column, and the only
-- ALTER TYPE is ADD VALUE, which takes nothing away from an enum.
-- Every statement is safe to run twice.


-- 3 new value(s) on existing types.

ALTER TYPE public.enum_pages_blocks_gallery_columns ADD VALUE IF NOT EXISTS '1' BEFORE '2';
ALTER TYPE public.enum_pages_blocks_people_columns ADD VALUE IF NOT EXISTS '1' BEFORE '2';
ALTER TYPE public.enum_pages_blocks_cards_columns ADD VALUE IF NOT EXISTS '1' BEFORE '2';

BEGIN;

-- 10 new type(s).

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_notice_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_notice_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_notice_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_notice_appearance_heading_size AS ENUM ('default', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_notice_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_notice_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_notice_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_notice_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_notice_tone AS ENUM ('warning', 'info', 'success');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_steps_steps_layout AS ENUM ('list', 'columns');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

-- 1 new table(s), with their types, keys and indexes.

CREATE TABLE IF NOT EXISTS public.pages_blocks_notice (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    tone public.enum_pages_blocks_notice_tone DEFAULT 'warning'::public.enum_pages_blocks_notice_tone,
    body jsonb,
    appearance_background public.enum_pages_blocks_notice_appearance_background DEFAULT 'default'::public.enum_pages_blocks_notice_appearance_background,
    appearance_text_theme public.enum_pages_blocks_notice_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_notice_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_notice_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_notice_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_notice_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_notice_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_notice_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_notice_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_notice_appearance_width DEFAULT 'default'::public.enum_pages_blocks_notice_appearance_width,
    appearance_align public.enum_pages_blocks_notice_appearance_align DEFAULT 'default'::public.enum_pages_blocks_notice_appearance_align,
    appearance_heading_size public.enum_pages_blocks_notice_appearance_heading_size DEFAULT 'default'::public.enum_pages_blocks_notice_appearance_heading_size,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_notice_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_notice ADD CONSTRAINT pages_blocks_notice_pkey PRIMARY KEY (id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS pages_blocks_notice_appearance_appearance_background_ima_idx ON public.pages_blocks_notice USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_notice_order_idx ON public.pages_blocks_notice USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_notice_parent_id_idx ON public.pages_blocks_notice USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_notice_path_idx ON public.pages_blocks_notice USING btree (_path);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_notice_appearance_background_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_notice ADD CONSTRAINT pages_blocks_notice_appearance_background_image_id_media_id_fk FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_notice_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_notice ADD CONSTRAINT pages_blocks_notice_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

-- New columns on 1 existing table(s).

ALTER TABLE public.pages_blocks_steps ADD COLUMN IF NOT EXISTS steps_layout enum_pages_blocks_steps_steps_layout DEFAULT 'list'::enum_pages_blocks_steps_steps_layout;

COMMIT;

