-- Tables behind the `shareWithContinents` field added to Posts and Events
-- (src/collections/fields/syndication.ts), which lets an article be released
-- to a whole continent instead of naming its country sites one by one.
--
-- Needed because `push` is development-only: a field added to a collection
-- reaches a local database by itself and never reaches the deployed one, and
-- until it does, every query that selects it fails.
--
-- Not hand-written. Generated by pushing the schema into a throwaway database
-- before and after adding the field and diffing the two dumps, so this is
-- exactly the shape Payload's Postgres adapter expects, index names included.
-- See scripts/README.md for the procedure.
--
-- Safe to run more than once. Adds only; drops nothing.

BEGIN;

DO $$
BEGIN
  CREATE TYPE public.enum_posts_share_with_continents AS ENUM
    ('africa', 'asia', 'europe', 'northamerica', 'southamerica', 'oceania');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_events_share_with_continents AS ENUM
    ('africa', 'asia', 'europe', 'northamerica', 'southamerica', 'oceania');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.posts_share_with_continents (
  "order"   integer NOT NULL,
  parent_id integer NOT NULL,
  value     public.enum_posts_share_with_continents,
  id        serial PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS public.events_share_with_continents (
  "order"   integer NOT NULL,
  parent_id integer NOT NULL,
  value     public.enum_events_share_with_continents,
  id        serial PRIMARY KEY NOT NULL
);

CREATE INDEX IF NOT EXISTS posts_share_with_continents_order_idx
  ON public.posts_share_with_continents USING btree ("order");
CREATE INDEX IF NOT EXISTS posts_share_with_continents_parent_idx
  ON public.posts_share_with_continents USING btree (parent_id);
CREATE INDEX IF NOT EXISTS events_share_with_continents_order_idx
  ON public.events_share_with_continents USING btree ("order");
CREATE INDEX IF NOT EXISTS events_share_with_continents_parent_idx
  ON public.events_share_with_continents USING btree (parent_id);

-- ON DELETE CASCADE so deleting an article takes its continent rows with it,
-- rather than leaving orphans that block the delete.
DO $$
BEGIN
  ALTER TABLE public.posts_share_with_continents
    ADD CONSTRAINT posts_share_with_continents_parent_fk
    FOREIGN KEY (parent_id) REFERENCES public.posts(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public.events_share_with_continents
    ADD CONSTRAINT events_share_with_continents_parent_fk
    FOREIGN KEY (parent_id) REFERENCES public.events(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMIT;

-- Check afterwards:
--   SELECT table_name FROM information_schema.tables
--   WHERE table_name LIKE '%share_with_continents';
