-- Generated by scripts/generate-catchup-sql.mjs. Do not hand-edit; regenerate.
-- 2026-09-04
--
-- 25 table(s), 1 column(s) on 1 existing table(s), 111 type(s).
--
-- Additive only: no DROP, no ALTER TYPE, no change to an existing column.
-- Every statement is safe to run twice.

BEGIN;

-- 111 new type(s).

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_accordion_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_accordion_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_accordion_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_accordion_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_accordion_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_accordion_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_accordion_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_banner_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_banner_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_banner_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_banner_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_banner_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_banner_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_banner_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_banner_buttons_style AS ENUM ('primary', 'secondary', 'link');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_banner_height AS ENUM ('sm', 'md', 'lg', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cards_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cards_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cards_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cards_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cards_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cards_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cards_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cards_columns AS ENUM ('2', '3', '4', '5');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cta_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cta_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cta_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cta_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cta_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cta_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cta_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_cta_buttons_style AS ENUM ('primary', 'secondary', 'link');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_embed_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_embed_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_embed_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_embed_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_embed_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_embed_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_embed_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_embed_ratio AS ENUM ('16-9', '1-1', '9-16', '21-9');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_gallery_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_gallery_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_gallery_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_gallery_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_gallery_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_gallery_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_gallery_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_gallery_columns AS ENUM ('2', '3', '4', '5');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_image_text_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_image_text_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_image_text_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_image_text_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_image_text_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_image_text_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_image_text_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_image_text_buttons_style AS ENUM ('primary', 'secondary', 'link');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_image_text_image_shape AS ENUM ('landscape', 'square', 'portrait', 'natural');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_image_text_image_side AS ENUM ('left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_logos_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_logos_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_logos_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_logos_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_logos_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_logos_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_logos_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_people_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_people_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_people_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_people_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_people_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_people_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_people_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_people_columns AS ENUM ('2', '3', '4', '5');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_prose_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_prose_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_prose_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_prose_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_prose_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_prose_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_prose_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_prose_buttons_style AS ENUM ('primary', 'secondary', 'link');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_quote_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_quote_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_quote_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_quote_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_quote_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_quote_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_quote_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_spacer_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_spacer_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_spacer_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_spacer_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_spacer_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_spacer_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_spacer_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_spacer_height AS ENUM ('sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_stats_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_stats_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_stats_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_stats_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_stats_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_stats_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_stats_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_steps_appearance_align AS ENUM ('default', 'left', 'center');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_steps_appearance_background AS ENUM ('default', 'white', 'paper', 'mist', 'brand', 'navy', 'night', 'colour', 'gradient', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_steps_appearance_focal_point AS ENUM ('center', 'top', 'bottom', 'left', 'right');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_steps_appearance_padding_bottom AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_steps_appearance_padding_top AS ENUM ('default', 'none', 'sm', 'md', 'lg', 'xl');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_steps_appearance_text_theme AS ENUM ('auto', 'dark', 'light');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_steps_appearance_width AS ENUM ('default', 'narrow', 'wide', 'full');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_pages_layout_mode AS ENUM ('inherit', 'before', 'after', 'replace');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

-- 25 new table(s), with their types, keys and indexes.

CREATE TABLE IF NOT EXISTS public.pages_blocks_accordion (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    appearance_background public.enum_pages_blocks_accordion_appearance_background DEFAULT 'default'::public.enum_pages_blocks_accordion_appearance_background,
    appearance_text_theme public.enum_pages_blocks_accordion_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_accordion_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_accordion_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_accordion_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_accordion_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_accordion_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_accordion_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_accordion_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_accordion_appearance_width DEFAULT 'default'::public.enum_pages_blocks_accordion_appearance_width,
    appearance_align public.enum_pages_blocks_accordion_appearance_align DEFAULT 'default'::public.enum_pages_blocks_accordion_appearance_align,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_accordion_items (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    question character varying NOT NULL,
    answer jsonb
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_banner (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    subheading character varying,
    show_breadcrumbs boolean DEFAULT true,
    height public.enum_pages_blocks_banner_height DEFAULT 'md'::public.enum_pages_blocks_banner_height,
    appearance_background public.enum_pages_blocks_banner_appearance_background DEFAULT 'default'::public.enum_pages_blocks_banner_appearance_background,
    appearance_text_theme public.enum_pages_blocks_banner_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_banner_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_banner_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_banner_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_banner_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_banner_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_banner_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_banner_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_banner_appearance_width DEFAULT 'default'::public.enum_pages_blocks_banner_appearance_width,
    appearance_align public.enum_pages_blocks_banner_appearance_align DEFAULT 'default'::public.enum_pages_blocks_banner_appearance_align,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_banner_buttons (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    label character varying NOT NULL,
    href character varying NOT NULL,
    style public.enum_pages_blocks_banner_buttons_style DEFAULT 'primary'::public.enum_pages_blocks_banner_buttons_style
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_cards (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    intro character varying,
    columns public.enum_pages_blocks_cards_columns DEFAULT '3'::public.enum_pages_blocks_cards_columns,
    appearance_background public.enum_pages_blocks_cards_appearance_background DEFAULT 'default'::public.enum_pages_blocks_cards_appearance_background,
    appearance_text_theme public.enum_pages_blocks_cards_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_cards_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_cards_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_cards_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_cards_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_cards_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_cards_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_cards_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_cards_appearance_width DEFAULT 'default'::public.enum_pages_blocks_cards_appearance_width,
    appearance_align public.enum_pages_blocks_cards_appearance_align DEFAULT 'default'::public.enum_pages_blocks_cards_appearance_align,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_cards_cards (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    image_id integer,
    tag character varying,
    title character varying NOT NULL,
    description character varying,
    href character varying,
    link_label character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_cta (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    description character varying,
    appearance_background public.enum_pages_blocks_cta_appearance_background DEFAULT 'default'::public.enum_pages_blocks_cta_appearance_background,
    appearance_text_theme public.enum_pages_blocks_cta_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_cta_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_cta_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_cta_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_cta_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_cta_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_cta_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_cta_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_cta_appearance_width DEFAULT 'default'::public.enum_pages_blocks_cta_appearance_width,
    appearance_align public.enum_pages_blocks_cta_appearance_align DEFAULT 'default'::public.enum_pages_blocks_cta_appearance_align,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_cta_buttons (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    label character varying NOT NULL,
    href character varying NOT NULL,
    style public.enum_pages_blocks_cta_buttons_style DEFAULT 'primary'::public.enum_pages_blocks_cta_buttons_style
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_embed (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    url character varying NOT NULL,
    ratio public.enum_pages_blocks_embed_ratio DEFAULT '16-9'::public.enum_pages_blocks_embed_ratio,
    caption character varying,
    appearance_background public.enum_pages_blocks_embed_appearance_background DEFAULT 'default'::public.enum_pages_blocks_embed_appearance_background,
    appearance_text_theme public.enum_pages_blocks_embed_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_embed_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_embed_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_embed_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_embed_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_embed_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_embed_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_embed_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_embed_appearance_width DEFAULT 'default'::public.enum_pages_blocks_embed_appearance_width,
    appearance_align public.enum_pages_blocks_embed_appearance_align DEFAULT 'default'::public.enum_pages_blocks_embed_appearance_align,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_gallery (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    columns public.enum_pages_blocks_gallery_columns DEFAULT '3'::public.enum_pages_blocks_gallery_columns,
    appearance_background public.enum_pages_blocks_gallery_appearance_background DEFAULT 'default'::public.enum_pages_blocks_gallery_appearance_background,
    appearance_text_theme public.enum_pages_blocks_gallery_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_gallery_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_gallery_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_gallery_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_gallery_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_gallery_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_gallery_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_gallery_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_gallery_appearance_width DEFAULT 'default'::public.enum_pages_blocks_gallery_appearance_width,
    appearance_align public.enum_pages_blocks_gallery_appearance_align DEFAULT 'default'::public.enum_pages_blocks_gallery_appearance_align,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_gallery_images (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    image_id integer NOT NULL,
    caption character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_image_text (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    body jsonb,
    image_id integer,
    image_side public.enum_pages_blocks_image_text_image_side DEFAULT 'right'::public.enum_pages_blocks_image_text_image_side,
    image_shape public.enum_pages_blocks_image_text_image_shape DEFAULT 'landscape'::public.enum_pages_blocks_image_text_image_shape,
    image_rounded boolean DEFAULT true,
    appearance_background public.enum_pages_blocks_image_text_appearance_background DEFAULT 'default'::public.enum_pages_blocks_image_text_appearance_background,
    appearance_text_theme public.enum_pages_blocks_image_text_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_image_text_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_image_text_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_image_text_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_image_text_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_image_text_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_image_text_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_image_text_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_image_text_appearance_width DEFAULT 'default'::public.enum_pages_blocks_image_text_appearance_width,
    appearance_align public.enum_pages_blocks_image_text_appearance_align DEFAULT 'default'::public.enum_pages_blocks_image_text_appearance_align,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_image_text_buttons (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    label character varying NOT NULL,
    href character varying NOT NULL,
    style public.enum_pages_blocks_image_text_buttons_style DEFAULT 'primary'::public.enum_pages_blocks_image_text_buttons_style
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_logos (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    appearance_background public.enum_pages_blocks_logos_appearance_background DEFAULT 'default'::public.enum_pages_blocks_logos_appearance_background,
    appearance_text_theme public.enum_pages_blocks_logos_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_logos_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_logos_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_logos_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_logos_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_logos_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_logos_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_logos_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_logos_appearance_width DEFAULT 'default'::public.enum_pages_blocks_logos_appearance_width,
    appearance_align public.enum_pages_blocks_logos_appearance_align DEFAULT 'default'::public.enum_pages_blocks_logos_appearance_align,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_logos_logos (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    image_id integer NOT NULL,
    name character varying,
    href character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_people (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    columns public.enum_pages_blocks_people_columns DEFAULT '3'::public.enum_pages_blocks_people_columns,
    appearance_background public.enum_pages_blocks_people_appearance_background DEFAULT 'default'::public.enum_pages_blocks_people_appearance_background,
    appearance_text_theme public.enum_pages_blocks_people_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_people_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_people_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_people_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_people_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_people_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_people_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_people_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_people_appearance_width DEFAULT 'default'::public.enum_pages_blocks_people_appearance_width,
    appearance_align public.enum_pages_blocks_people_appearance_align DEFAULT 'default'::public.enum_pages_blocks_people_appearance_align,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_people_people (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    photo_id integer,
    name character varying NOT NULL,
    role character varying,
    bio character varying,
    email character varying,
    starts_row boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_prose (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    body jsonb,
    appearance_background public.enum_pages_blocks_prose_appearance_background DEFAULT 'default'::public.enum_pages_blocks_prose_appearance_background,
    appearance_text_theme public.enum_pages_blocks_prose_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_prose_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_prose_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_prose_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_prose_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_prose_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_prose_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_prose_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_prose_appearance_width DEFAULT 'default'::public.enum_pages_blocks_prose_appearance_width,
    appearance_align public.enum_pages_blocks_prose_appearance_align DEFAULT 'default'::public.enum_pages_blocks_prose_appearance_align,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_prose_buttons (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    label character varying NOT NULL,
    href character varying NOT NULL,
    style public.enum_pages_blocks_prose_buttons_style DEFAULT 'primary'::public.enum_pages_blocks_prose_buttons_style
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_quote (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    quote character varying NOT NULL,
    attribution character varying,
    role character varying,
    image_id integer,
    appearance_background public.enum_pages_blocks_quote_appearance_background DEFAULT 'default'::public.enum_pages_blocks_quote_appearance_background,
    appearance_text_theme public.enum_pages_blocks_quote_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_quote_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_quote_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_quote_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_quote_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_quote_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_quote_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_quote_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_quote_appearance_width DEFAULT 'default'::public.enum_pages_blocks_quote_appearance_width,
    appearance_align public.enum_pages_blocks_quote_appearance_align DEFAULT 'default'::public.enum_pages_blocks_quote_appearance_align,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_spacer (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    height public.enum_pages_blocks_spacer_height DEFAULT 'md'::public.enum_pages_blocks_spacer_height,
    rule boolean DEFAULT false,
    appearance_background public.enum_pages_blocks_spacer_appearance_background DEFAULT 'default'::public.enum_pages_blocks_spacer_appearance_background,
    appearance_text_theme public.enum_pages_blocks_spacer_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_spacer_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_spacer_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_spacer_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_spacer_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_spacer_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_spacer_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_spacer_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_spacer_appearance_width DEFAULT 'default'::public.enum_pages_blocks_spacer_appearance_width,
    appearance_align public.enum_pages_blocks_spacer_appearance_align DEFAULT 'default'::public.enum_pages_blocks_spacer_appearance_align,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_stats (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    appearance_background public.enum_pages_blocks_stats_appearance_background DEFAULT 'default'::public.enum_pages_blocks_stats_appearance_background,
    appearance_text_theme public.enum_pages_blocks_stats_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_stats_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_stats_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_stats_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_stats_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_stats_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_stats_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_stats_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_stats_appearance_width DEFAULT 'default'::public.enum_pages_blocks_stats_appearance_width,
    appearance_align public.enum_pages_blocks_stats_appearance_align DEFAULT 'default'::public.enum_pages_blocks_stats_appearance_align,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_stats_stats (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    value character varying NOT NULL,
    label character varying NOT NULL
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_steps (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    appearance_background public.enum_pages_blocks_steps_appearance_background DEFAULT 'default'::public.enum_pages_blocks_steps_appearance_background,
    appearance_text_theme public.enum_pages_blocks_steps_appearance_text_theme DEFAULT 'auto'::public.enum_pages_blocks_steps_appearance_text_theme,
    appearance_background_colour character varying,
    appearance_gradient_from character varying,
    appearance_gradient_to character varying,
    appearance_gradient_angle numeric,
    appearance_background_image_id integer,
    appearance_overlay numeric,
    appearance_overlay_colour character varying,
    appearance_focal_point public.enum_pages_blocks_steps_appearance_focal_point DEFAULT 'center'::public.enum_pages_blocks_steps_appearance_focal_point,
    appearance_padding_top public.enum_pages_blocks_steps_appearance_padding_top DEFAULT 'default'::public.enum_pages_blocks_steps_appearance_padding_top,
    appearance_padding_bottom public.enum_pages_blocks_steps_appearance_padding_bottom DEFAULT 'default'::public.enum_pages_blocks_steps_appearance_padding_bottom,
    appearance_width public.enum_pages_blocks_steps_appearance_width DEFAULT 'default'::public.enum_pages_blocks_steps_appearance_width,
    appearance_align public.enum_pages_blocks_steps_appearance_align DEFAULT 'default'::public.enum_pages_blocks_steps_appearance_align,
    appearance_accent_colour character varying,
    appearance_anchor character varying,
    appearance_hidden boolean DEFAULT false,
    block_name character varying
);

CREATE TABLE IF NOT EXISTS public.pages_blocks_steps_steps (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    title character varying NOT NULL,
    description character varying,
    href character varying
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_accordion_items_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_accordion_items ADD CONSTRAINT pages_blocks_accordion_items_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_accordion_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_accordion ADD CONSTRAINT pages_blocks_accordion_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_banner_buttons_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_banner_buttons ADD CONSTRAINT pages_blocks_banner_buttons_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_banner_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_banner ADD CONSTRAINT pages_blocks_banner_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_cards_cards_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_cards_cards ADD CONSTRAINT pages_blocks_cards_cards_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_cards_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_cards ADD CONSTRAINT pages_blocks_cards_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_cta_buttons_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_cta_buttons ADD CONSTRAINT pages_blocks_cta_buttons_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_cta_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_cta ADD CONSTRAINT pages_blocks_cta_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_embed_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_embed ADD CONSTRAINT pages_blocks_embed_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_gallery_images_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_gallery_images ADD CONSTRAINT pages_blocks_gallery_images_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_gallery_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_gallery ADD CONSTRAINT pages_blocks_gallery_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_image_text_buttons_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_image_text_buttons ADD CONSTRAINT pages_blocks_image_text_buttons_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_image_text_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_image_text ADD CONSTRAINT pages_blocks_image_text_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_logos_logos_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_logos_logos ADD CONSTRAINT pages_blocks_logos_logos_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_logos_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_logos ADD CONSTRAINT pages_blocks_logos_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_people_people_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_people_people ADD CONSTRAINT pages_blocks_people_people_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_people_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_people ADD CONSTRAINT pages_blocks_people_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_prose_buttons_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_prose_buttons ADD CONSTRAINT pages_blocks_prose_buttons_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_prose_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_prose ADD CONSTRAINT pages_blocks_prose_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_quote_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_quote ADD CONSTRAINT pages_blocks_quote_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_spacer_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_spacer ADD CONSTRAINT pages_blocks_spacer_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_stats_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_stats ADD CONSTRAINT pages_blocks_stats_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_stats_stats_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_stats_stats ADD CONSTRAINT pages_blocks_stats_stats_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_steps_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_steps ADD CONSTRAINT pages_blocks_steps_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_steps_steps_pkey' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_steps_steps ADD CONSTRAINT pages_blocks_steps_steps_pkey PRIMARY KEY (id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS pages_blocks_accordion_appearance_appearance_background__idx ON public.pages_blocks_accordion USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_accordion_items_order_idx ON public.pages_blocks_accordion_items USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_accordion_items_parent_id_idx ON public.pages_blocks_accordion_items USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_accordion_order_idx ON public.pages_blocks_accordion USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_accordion_parent_id_idx ON public.pages_blocks_accordion USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_accordion_path_idx ON public.pages_blocks_accordion USING btree (_path);

CREATE INDEX IF NOT EXISTS pages_blocks_banner_appearance_appearance_background_ima_idx ON public.pages_blocks_banner USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_banner_buttons_order_idx ON public.pages_blocks_banner_buttons USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_banner_buttons_parent_id_idx ON public.pages_blocks_banner_buttons USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_banner_order_idx ON public.pages_blocks_banner USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_banner_parent_id_idx ON public.pages_blocks_banner USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_banner_path_idx ON public.pages_blocks_banner USING btree (_path);

CREATE INDEX IF NOT EXISTS pages_blocks_cards_appearance_appearance_background_imag_idx ON public.pages_blocks_cards USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_cards_cards_image_idx ON public.pages_blocks_cards_cards USING btree (image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_cards_cards_order_idx ON public.pages_blocks_cards_cards USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_cards_cards_parent_id_idx ON public.pages_blocks_cards_cards USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_cards_order_idx ON public.pages_blocks_cards USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_cards_parent_id_idx ON public.pages_blocks_cards USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_cards_path_idx ON public.pages_blocks_cards USING btree (_path);

CREATE INDEX IF NOT EXISTS pages_blocks_cta_appearance_appearance_background_image_idx ON public.pages_blocks_cta USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_cta_buttons_order_idx ON public.pages_blocks_cta_buttons USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_cta_buttons_parent_id_idx ON public.pages_blocks_cta_buttons USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_cta_order_idx ON public.pages_blocks_cta USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_cta_parent_id_idx ON public.pages_blocks_cta USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_cta_path_idx ON public.pages_blocks_cta USING btree (_path);

CREATE INDEX IF NOT EXISTS pages_blocks_embed_appearance_appearance_background_imag_idx ON public.pages_blocks_embed USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_embed_order_idx ON public.pages_blocks_embed USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_embed_parent_id_idx ON public.pages_blocks_embed USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_embed_path_idx ON public.pages_blocks_embed USING btree (_path);

CREATE INDEX IF NOT EXISTS pages_blocks_gallery_appearance_appearance_background_im_idx ON public.pages_blocks_gallery USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_gallery_images_image_idx ON public.pages_blocks_gallery_images USING btree (image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_gallery_images_order_idx ON public.pages_blocks_gallery_images USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_gallery_images_parent_id_idx ON public.pages_blocks_gallery_images USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_gallery_order_idx ON public.pages_blocks_gallery USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_gallery_parent_id_idx ON public.pages_blocks_gallery USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_gallery_path_idx ON public.pages_blocks_gallery USING btree (_path);

CREATE INDEX IF NOT EXISTS pages_blocks_image_text_appearance_appearance_background_idx ON public.pages_blocks_image_text USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_image_text_buttons_order_idx ON public.pages_blocks_image_text_buttons USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_image_text_buttons_parent_id_idx ON public.pages_blocks_image_text_buttons USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_image_text_image_idx ON public.pages_blocks_image_text USING btree (image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_image_text_order_idx ON public.pages_blocks_image_text USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_image_text_parent_id_idx ON public.pages_blocks_image_text USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_image_text_path_idx ON public.pages_blocks_image_text USING btree (_path);

CREATE INDEX IF NOT EXISTS pages_blocks_logos_appearance_appearance_background_imag_idx ON public.pages_blocks_logos USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_logos_logos_image_idx ON public.pages_blocks_logos_logos USING btree (image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_logos_logos_order_idx ON public.pages_blocks_logos_logos USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_logos_logos_parent_id_idx ON public.pages_blocks_logos_logos USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_logos_order_idx ON public.pages_blocks_logos USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_logos_parent_id_idx ON public.pages_blocks_logos USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_logos_path_idx ON public.pages_blocks_logos USING btree (_path);

CREATE INDEX IF NOT EXISTS pages_blocks_people_appearance_appearance_background_ima_idx ON public.pages_blocks_people USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_people_order_idx ON public.pages_blocks_people USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_people_parent_id_idx ON public.pages_blocks_people USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_people_path_idx ON public.pages_blocks_people USING btree (_path);

CREATE INDEX IF NOT EXISTS pages_blocks_people_people_order_idx ON public.pages_blocks_people_people USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_people_people_parent_id_idx ON public.pages_blocks_people_people USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_people_people_photo_idx ON public.pages_blocks_people_people USING btree (photo_id);

CREATE INDEX IF NOT EXISTS pages_blocks_prose_appearance_appearance_background_imag_idx ON public.pages_blocks_prose USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_prose_buttons_order_idx ON public.pages_blocks_prose_buttons USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_prose_buttons_parent_id_idx ON public.pages_blocks_prose_buttons USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_prose_order_idx ON public.pages_blocks_prose USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_prose_parent_id_idx ON public.pages_blocks_prose USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_prose_path_idx ON public.pages_blocks_prose USING btree (_path);

CREATE INDEX IF NOT EXISTS pages_blocks_quote_appearance_appearance_background_imag_idx ON public.pages_blocks_quote USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_quote_image_idx ON public.pages_blocks_quote USING btree (image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_quote_order_idx ON public.pages_blocks_quote USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_quote_parent_id_idx ON public.pages_blocks_quote USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_quote_path_idx ON public.pages_blocks_quote USING btree (_path);

CREATE INDEX IF NOT EXISTS pages_blocks_spacer_appearance_appearance_background_ima_idx ON public.pages_blocks_spacer USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_spacer_order_idx ON public.pages_blocks_spacer USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_spacer_parent_id_idx ON public.pages_blocks_spacer USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_spacer_path_idx ON public.pages_blocks_spacer USING btree (_path);

CREATE INDEX IF NOT EXISTS pages_blocks_stats_appearance_appearance_background_imag_idx ON public.pages_blocks_stats USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_stats_order_idx ON public.pages_blocks_stats USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_stats_parent_id_idx ON public.pages_blocks_stats USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_stats_path_idx ON public.pages_blocks_stats USING btree (_path);

CREATE INDEX IF NOT EXISTS pages_blocks_stats_stats_order_idx ON public.pages_blocks_stats_stats USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_stats_stats_parent_id_idx ON public.pages_blocks_stats_stats USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_steps_appearance_appearance_background_imag_idx ON public.pages_blocks_steps USING btree (appearance_background_image_id);

CREATE INDEX IF NOT EXISTS pages_blocks_steps_order_idx ON public.pages_blocks_steps USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_steps_parent_id_idx ON public.pages_blocks_steps USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS pages_blocks_steps_path_idx ON public.pages_blocks_steps USING btree (_path);

CREATE INDEX IF NOT EXISTS pages_blocks_steps_steps_order_idx ON public.pages_blocks_steps_steps USING btree (_order);

CREATE INDEX IF NOT EXISTS pages_blocks_steps_steps_parent_id_idx ON public.pages_blocks_steps_steps USING btree (_parent_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_accordion_appearance_background_image_id_media_id_' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_accordion ADD CONSTRAINT pages_blocks_accordion_appearance_background_image_id_media_id_ FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_accordion_items_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_accordion_items ADD CONSTRAINT pages_blocks_accordion_items_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages_blocks_accordion(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_accordion_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_accordion ADD CONSTRAINT pages_blocks_accordion_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_banner_appearance_background_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_banner ADD CONSTRAINT pages_blocks_banner_appearance_background_image_id_media_id_fk FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_banner_buttons_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_banner_buttons ADD CONSTRAINT pages_blocks_banner_buttons_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages_blocks_banner(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_banner_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_banner ADD CONSTRAINT pages_blocks_banner_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_cards_appearance_background_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_cards ADD CONSTRAINT pages_blocks_cards_appearance_background_image_id_media_id_fk FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_cards_cards_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_cards_cards ADD CONSTRAINT pages_blocks_cards_cards_image_id_media_id_fk FOREIGN KEY (image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_cards_cards_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_cards_cards ADD CONSTRAINT pages_blocks_cards_cards_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages_blocks_cards(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_cards_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_cards ADD CONSTRAINT pages_blocks_cards_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_cta_appearance_background_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_cta ADD CONSTRAINT pages_blocks_cta_appearance_background_image_id_media_id_fk FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_cta_buttons_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_cta_buttons ADD CONSTRAINT pages_blocks_cta_buttons_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages_blocks_cta(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_cta_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_cta ADD CONSTRAINT pages_blocks_cta_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_embed_appearance_background_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_embed ADD CONSTRAINT pages_blocks_embed_appearance_background_image_id_media_id_fk FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_embed_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_embed ADD CONSTRAINT pages_blocks_embed_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_gallery_appearance_background_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_gallery ADD CONSTRAINT pages_blocks_gallery_appearance_background_image_id_media_id_fk FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_gallery_images_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_gallery_images ADD CONSTRAINT pages_blocks_gallery_images_image_id_media_id_fk FOREIGN KEY (image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_gallery_images_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_gallery_images ADD CONSTRAINT pages_blocks_gallery_images_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages_blocks_gallery(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_gallery_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_gallery ADD CONSTRAINT pages_blocks_gallery_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_image_text_appearance_background_image_id_media_id' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_image_text ADD CONSTRAINT pages_blocks_image_text_appearance_background_image_id_media_id FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_image_text_buttons_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_image_text_buttons ADD CONSTRAINT pages_blocks_image_text_buttons_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages_blocks_image_text(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_image_text_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_image_text ADD CONSTRAINT pages_blocks_image_text_image_id_media_id_fk FOREIGN KEY (image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_image_text_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_image_text ADD CONSTRAINT pages_blocks_image_text_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_logos_appearance_background_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_logos ADD CONSTRAINT pages_blocks_logos_appearance_background_image_id_media_id_fk FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_logos_logos_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_logos_logos ADD CONSTRAINT pages_blocks_logos_logos_image_id_media_id_fk FOREIGN KEY (image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_logos_logos_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_logos_logos ADD CONSTRAINT pages_blocks_logos_logos_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages_blocks_logos(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_logos_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_logos ADD CONSTRAINT pages_blocks_logos_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_people_appearance_background_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_people ADD CONSTRAINT pages_blocks_people_appearance_background_image_id_media_id_fk FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_people_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_people ADD CONSTRAINT pages_blocks_people_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_people_people_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_people_people ADD CONSTRAINT pages_blocks_people_people_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages_blocks_people(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_people_people_photo_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_people_people ADD CONSTRAINT pages_blocks_people_people_photo_id_media_id_fk FOREIGN KEY (photo_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_prose_appearance_background_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_prose ADD CONSTRAINT pages_blocks_prose_appearance_background_image_id_media_id_fk FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_prose_buttons_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_prose_buttons ADD CONSTRAINT pages_blocks_prose_buttons_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages_blocks_prose(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_prose_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_prose ADD CONSTRAINT pages_blocks_prose_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_quote_appearance_background_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_quote ADD CONSTRAINT pages_blocks_quote_appearance_background_image_id_media_id_fk FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_quote_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_quote ADD CONSTRAINT pages_blocks_quote_image_id_media_id_fk FOREIGN KEY (image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_quote_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_quote ADD CONSTRAINT pages_blocks_quote_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_spacer_appearance_background_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_spacer ADD CONSTRAINT pages_blocks_spacer_appearance_background_image_id_media_id_fk FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_spacer_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_spacer ADD CONSTRAINT pages_blocks_spacer_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_stats_appearance_background_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_stats ADD CONSTRAINT pages_blocks_stats_appearance_background_image_id_media_id_fk FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_stats_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_stats ADD CONSTRAINT pages_blocks_stats_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_stats_stats_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_stats_stats ADD CONSTRAINT pages_blocks_stats_stats_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages_blocks_stats(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_steps_appearance_background_image_id_media_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_steps ADD CONSTRAINT pages_blocks_steps_appearance_background_image_id_media_id_fk FOREIGN KEY (appearance_background_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_steps_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_steps ADD CONSTRAINT pages_blocks_steps_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pages_blocks_steps_steps_parent_id_fk' AND connamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE ONLY public.pages_blocks_steps_steps ADD CONSTRAINT pages_blocks_steps_steps_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.pages_blocks_steps(id) ON DELETE CASCADE;
  END IF;
END $$;

-- New columns on 1 existing table(s).

ALTER TABLE public.pages ADD COLUMN IF NOT EXISTS layout_mode enum_pages_layout_mode DEFAULT 'inherit'::enum_pages_layout_mode;

COMMIT;

