-- Generated by scripts/generate-catchup-sql.mjs. Do not hand-edit; regenerate.
-- 2026-09-06
--
-- 0 table(s), 1 column(s) on 1 existing table(s), 1 type(s), 0 value(s) on 0 existing type(s).
--
-- Additive only: no DROP, no change to an existing column, and the only
-- ALTER TYPE is ADD VALUE, which takes nothing away from an enum.
-- Every statement is safe to run twice.


BEGIN;

-- 1 new type(s).

DO $$
BEGIN
  CREATE TYPE public.enum_pages_blocks_image_text_image_size AS ENUM ('full', 'medium', 'small');
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN duplicate_table THEN NULL;
  WHEN duplicate_column THEN NULL;
END $$;

-- New columns on 1 existing table(s).

ALTER TABLE public.pages_blocks_image_text ADD COLUMN IF NOT EXISTS image_size enum_pages_blocks_image_text_image_size DEFAULT 'full'::enum_pages_blocks_image_text_image_size;

COMMIT;

