-- The traffic counters behind /admin/traffic.
--
-- One row is one number: "on this day, on this country site, this page was
-- opened 41 times". A page view does not add a row, it adds one to the rows
-- that already describe it, so the table stays small however busy the site
-- gets. The unique index on (day, site, kind, label) is what makes that
-- work — without it every view would insert instead of increment, and
-- /api/track's `ON CONFLICT` would have nothing to conflict against.
--
-- Nothing here identifies anybody: no address is stored, no cookie is set,
-- and a "visit" is counted from a flag that lives only in the reader's open
-- tab.
--
-- Needed because `push` is development-only: a collection added in code
-- creates its table on your machine and never on the deployed one. Until this
-- runs, /admin/traffic reports nothing and every view is silently dropped.
-- See scripts/README.md.
--
-- Not hand-written. Generated by pushing the schema into a throwaway database
-- and reading the tables back, so this is the shape Payload's Postgres adapter
-- expects.
--
-- Safe to run more than once. Adds only; drops nothing.

DO $$ BEGIN
  CREATE TYPE "public"."enum_traffic_kind" AS ENUM ('total', 'page', 'referrer', 'country');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "public"."traffic" (
  "id" serial PRIMARY KEY,
  "day" varchar NOT NULL,
  "site" varchar DEFAULT '' NOT NULL,
  "kind" "public"."enum_traffic_kind" NOT NULL,
  "label" varchar DEFAULT '' NOT NULL,
  "views" numeric DEFAULT 0 NOT NULL,
  "visits" numeric DEFAULT 0 NOT NULL,
  "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
);

-- What turns a view into an increment rather than a new row.
CREATE UNIQUE INDEX IF NOT EXISTS "day_site_kind_label_idx"
  ON "public"."traffic" USING btree ("day", "site", "kind", "label");
CREATE INDEX IF NOT EXISTS "traffic_day_idx"
  ON "public"."traffic" USING btree ("day");
CREATE INDEX IF NOT EXISTS "traffic_created_at_idx"
  ON "public"."traffic" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "traffic_updated_at_idx"
  ON "public"."traffic" USING btree ("updated_at");

-- Payload keeps a row here for every document being edited, with one column
-- per collection. A missing column takes out the whole admin, not just this
-- screen, because every document open writes through this table.
ALTER TABLE "public"."payload_locked_documents_rels"
  ADD COLUMN IF NOT EXISTS "traffic_id" integer;

DO $$ BEGIN
  ALTER TABLE "public"."payload_locked_documents_rels"
    ADD CONSTRAINT "payload_locked_documents_rels_traffic_fk"
    FOREIGN KEY ("traffic_id") REFERENCES "public"."traffic"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "payload_locked_documents_rels_traffic_id_idx"
  ON "public"."payload_locked_documents_rels" USING btree ("traffic_id");
