-- Roles and per-country permissions on Users (src/collections/Users.ts), which
-- is what scopes /admin: a country admin sees only the sections and the
-- country sites listed on their account.
--
-- Needed because `push` is development-only: fields added to a collection
-- reach a local database by itself and never reach the deployed one, and until
-- they do, every query that selects them fails — which for Users means nobody
-- can sign in to the admin at all. See scripts/README.md.
--
-- Not hand-written. Generated by pushing the schema into a throwaway database
-- and taking the new objects out of its pg_dump, so this is exactly the shape
-- Payload's Postgres adapter expects, index and constraint names included.
--
-- Safe to run more than once. Adds only; drops nothing.
--
-- Deliberately not wrapped in a transaction: the enum types have to exist and
-- be committed before the columns that use them are added.

DO $$
BEGIN
  CREATE TYPE public.enum_users_role AS ENUM ('super-admin', 'country-admin');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.enum_users_sections AS ENUM (
    'pages',
    'posts',
    'events',
    'campuses',
    'tenant-content',
    'media',
    'ministries',
    'bible-study-signups',
    'volunteer-applications',
    'internship-applications',
    'chapter-affiliations',
    'membership-applications',
    'contact-messages',
    'donation-intents'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Everyone who can already sign in becomes a super admin. Anything else would
-- lock the existing accounts out of their own admin the moment this runs; new
-- accounts default to country admin, which is the safe direction.
ALTER TABLE "public"."users"
  ADD COLUMN IF NOT EXISTS "role" public.enum_users_role
  DEFAULT 'country-admin'::public.enum_users_role NOT NULL;

UPDATE "public"."users" SET "role" = 'super-admin' WHERE "role" = 'country-admin';

-- The countries a user administers. Payload keeps `hasMany` relationships in a
-- side table shared by every relationship on the collection, hence `path`.
CREATE TABLE IF NOT EXISTS "public"."users_rels" (
  "id" integer NOT NULL,
  "order" integer,
  "parent_id" integer NOT NULL,
  "path" character varying NOT NULL,
  "tenants_id" integer
);

CREATE SEQUENCE IF NOT EXISTS "public"."users_rels_id_seq"
  AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE "public"."users_rels_id_seq" OWNED BY "public"."users_rels"."id";
ALTER TABLE ONLY "public"."users_rels"
  ALTER COLUMN "id" SET DEFAULT nextval('public.users_rels_id_seq'::regclass);

-- The sections of the admin they can open.
CREATE TABLE IF NOT EXISTS "public"."users_sections" (
  "order" integer NOT NULL,
  "parent_id" integer NOT NULL,
  "value" public.enum_users_sections,
  "id" integer NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS "public"."users_sections_id_seq"
  AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE "public"."users_sections_id_seq" OWNED BY "public"."users_sections"."id";
ALTER TABLE ONLY "public"."users_sections"
  ALTER COLUMN "id" SET DEFAULT nextval('public.users_sections_id_seq'::regclass);

-- Catalogue checks rather than an exception handler: a repeated primary key
-- raises invalid_table_definition, which `EXCEPTION WHEN duplicate_object`
-- does not catch.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_rels_pkey') THEN
    ALTER TABLE ONLY "public"."users_rels" ADD CONSTRAINT "users_rels_pkey" PRIMARY KEY ("id");
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_sections_pkey') THEN
    ALTER TABLE ONLY "public"."users_sections" ADD CONSTRAINT "users_sections_pkey" PRIMARY KEY ("id");
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_rels_parent_fk') THEN
    ALTER TABLE ONLY "public"."users_rels" ADD CONSTRAINT "users_rels_parent_fk"
      FOREIGN KEY ("parent_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_rels_tenants_fk') THEN
    ALTER TABLE ONLY "public"."users_rels" ADD CONSTRAINT "users_rels_tenants_fk"
      FOREIGN KEY ("tenants_id") REFERENCES "public"."tenants"("id") ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_sections_parent_fk') THEN
    ALTER TABLE ONLY "public"."users_sections" ADD CONSTRAINT "users_sections_parent_fk"
      FOREIGN KEY ("parent_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "users_rels_order_idx" ON "public"."users_rels" USING btree ("order");
CREATE INDEX IF NOT EXISTS "users_rels_parent_idx" ON "public"."users_rels" USING btree ("parent_id");
CREATE INDEX IF NOT EXISTS "users_rels_path_idx" ON "public"."users_rels" USING btree ("path");
CREATE INDEX IF NOT EXISTS "users_rels_tenants_id_idx" ON "public"."users_rels" USING btree ("tenants_id");
CREATE INDEX IF NOT EXISTS "users_sections_order_idx" ON "public"."users_sections" USING btree ("order");
CREATE INDEX IF NOT EXISTS "users_sections_parent_idx" ON "public"."users_sections" USING btree ("parent_id");
