-- Generated by scripts/generate-catchup-sql.mjs. Do not hand-edit; regenerate.
-- 2026-09-06
--
-- 0 table(s), 1 column(s) on 1 existing table(s), 0 type(s), 0 value(s) on 0 existing type(s).
--
-- Additive only: no DROP, no change to an existing column, and the only
-- ALTER TYPE is ADD VALUE, which takes nothing away from an enum.
-- Every statement is safe to run twice.


BEGIN;

-- New columns on 1 existing table(s).

ALTER TABLE public.pages_blocks_people_people ADD COLUMN IF NOT EXISTS featured boolean DEFAULT false;

COMMIT;

