-- The `description` field added to each card of the Get Involved Cards block
-- (src/collections/blocks/homeBlocks.ts), which the design puts under the
-- card's title, plus the eight message keys the new copy introduced.
--
-- Needed because `push` is development-only: a field added to a block reaches
-- a local database by itself and never reaches the deployed one, and until it
-- does, every query that selects it fails. See scripts/README.md.
--
-- The enum is the list of strings a country site is allowed to override. It is
-- derived from messages/en.json (src/lib/messageKeys.ts), so adding copy to
-- that file adds values here too; without them, saving a Country copy row for
-- one of the new keys fails with 'invalid input value for enum'.
--
-- Not hand-written. Generated by pushing the schema into a throwaway database
-- before and after the change and diffing the two dumps, so this is exactly
-- the shape Payload's Postgres adapter expects.
--
-- Safe to run more than once. Adds only; drops nothing.
--
-- Deliberately not wrapped in a transaction: ADD VALUE and using the value
-- cannot share one.

ALTER TABLE "public"."pages_blocks_get_involved_cards"
  ADD COLUMN IF NOT EXISTS "description" varchar;

-- BEFORE, not a bare append: a freshly pushed database creates these values in
-- sorted order, and scripts/inventory-schema.mjs reads them back in enum sort
-- order. Appending would leave the deployed database reporting a different
-- order from a pushed one and every future schema diff would show it.
ALTER TYPE "public"."enum_tenant_content_overrides_key" ADD VALUE IF NOT EXISTS 'Home.GetInvolved.discipleshipTraining' BEFORE 'Home.GetInvolved.eyebrow';
ALTER TYPE "public"."enum_tenant_content_overrides_key" ADD VALUE IF NOT EXISTS 'Home.GetInvolved.discipleshipTrainingDescription' BEFORE 'Home.GetInvolved.eyebrow';
ALTER TYPE "public"."enum_tenant_content_overrides_key" ADD VALUE IF NOT EXISTS 'Home.GetInvolved.missionTrip' BEFORE 'Home.GetInvolved.volunteer';
ALTER TYPE "public"."enum_tenant_content_overrides_key" ADD VALUE IF NOT EXISTS 'Home.GetInvolved.missionTripDescription' BEFORE 'Home.GetInvolved.volunteer';
ALTER TYPE "public"."enum_tenant_content_overrides_key" ADD VALUE IF NOT EXISTS 'Home.GetInvolved.shortTermMission' BEFORE 'Home.GetInvolved.volunteer';
ALTER TYPE "public"."enum_tenant_content_overrides_key" ADD VALUE IF NOT EXISTS 'Home.GetInvolved.shortTermMissionDescription' BEFORE 'Home.GetInvolved.volunteer';
ALTER TYPE "public"."enum_tenant_content_overrides_key" ADD VALUE IF NOT EXISTS 'Home.GetInvolved.volunteering' BEFORE 'Home.Hero.dragToExplore';
ALTER TYPE "public"."enum_tenant_content_overrides_key" ADD VALUE IF NOT EXISTS 'Home.GetInvolved.volunteeringDescription' BEFORE 'Home.Hero.dragToExplore';
