-- Generated by scripts/generate-catchup-sql.mjs. Do not hand-edit; regenerate.
-- 2026-09-06
--
-- 0 table(s), 0 column(s) on 0 existing table(s), 0 type(s), 1 value(s) on 1 existing type(s).
--
-- Additive only: no DROP, no change to an existing column, and the only
-- ALTER TYPE is ADD VALUE, which takes nothing away from an enum.
-- Every statement is safe to run twice.


-- 1 new value(s) on existing types.

ALTER TYPE public.enum_pages_blocks_gallery_image_shape ADD VALUE IF NOT EXISTS 'natural';

BEGIN;

COMMIT;

