/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    campuses: Campus;
    events: Event;
    posts: Post;
    ministries: Ministry;
    'bible-study-signups': BibleStudySignup;
    'volunteer-applications': VolunteerApplication;
    tenants: Tenant;
    'tenant-content': TenantContent;
    pages: Page;
    'contact-messages': ContactMessage;
    'donation-intents': DonationIntent;
    partners: Partner;
    invoices: Invoice;
    'chapter-affiliations': ChapterAffiliation;
    'membership-applications': MembershipApplication;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    campuses: CampusesSelect<false> | CampusesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    ministries: MinistriesSelect<false> | MinistriesSelect<true>;
    'bible-study-signups': BibleStudySignupsSelect<false> | BibleStudySignupsSelect<true>;
    'volunteer-applications': VolunteerApplicationsSelect<false> | VolunteerApplicationsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'tenant-content': TenantContentSelect<false> | TenantContentSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'donation-intents': DonationIntentsSelect<false> | DonationIntentsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    'chapter-affiliations': ChapterAffiliationsSelect<false> | ChapterAffiliationsSelect<true>;
    'membership-applications': MembershipApplicationsSelect<false> | MembershipApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campuses".
 */
export interface Campus {
  id: number;
  name: string;
  /**
   * City, State — shown next to the chapter name.
   */
  location: string;
  active?: boolean | null;
  /**
   * Leave empty for a main-site (US) chapter. Set this to show the chapter on that country site's network search instead.
   */
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * One entry per country site. The URL is /{continent}/{slug}, e.g. continent 'europe' + slug 'germany' -> amintl.org/europe/germany.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * e.g. "Germany"
   */
  country: string;
  /**
   * Main chapter city, e.g. "Frankfurt" — shown on the Our Network page.
   */
  city?: string | null;
  continent: 'africa' | 'asia' | 'europe' | 'northamerica' | 'southamerica' | 'oceania';
  /**
   * URL segment, e.g. "germany" for /europe/germany
   */
  slug: string;
  /**
   * Default site language for this country, used for the geo-suggestion banner. Only languages the site is translated into can be chosen — see Spoken languages for the gap.
   */
  locale?:
    | (
        | 'en'
        | 'es'
        | 'fr'
        | 'de'
        | 'pt'
        | 'ko'
        | 'ja'
        | 'zh'
        | 'it'
        | 'ru'
        | 'tr'
        | 'id'
        | 'nl'
        | 'pl'
        | 'uk'
        | 'cs'
        | 'sk'
        | 'el'
        | 'hu'
        | 'ro'
        | 'sv'
        | 'ar'
        | 'he'
        | 'ur'
        | 'hi'
        | 'bn'
        | 'ta'
        | 'ne'
        | 'si'
        | 'my'
        | 'th'
        | 'vi'
        | 'fil'
        | 'ms'
        | 'mn'
        | 'kk'
        | 'sw'
        | 'am'
        | 'af'
        | 'zu'
        | 'xh'
        | 'rw'
        | 'rn'
        | 'mg'
        | 'ht'
        | 'fj'
        | 'hif'
        | 'rm'
      )
    | null;
  /**
   * Comma-separated ISO country codes this tenant matches for IP-based geo detection, e.g. "DE" or "DE,AT". A code must belong to exactly one tenant.
   */
  countryCodes?: string | null;
  /**
   * Languages actually spoken here, as comma-separated BCP 47 tags (e.g. "cs" for Czechia). Where one of these is not in the Default language list above, the country is reading the site in a fallback language and is waiting on a translation.
   */
  languages?: string | null;
  /**
   * Which half of AM's G20 + M40 mission country list this came from.
   */
  tier?: ('g20' | 'm40') | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * URL segment, e.g. "spring-retreat-2026"
   */
  slug: string;
  coverImage?: (number | null) | Media;
  location?: string | null;
  excerpt?: string | null;
  /**
   * How the date is displayed, e.g. "April 4–5" or "February 18".
   */
  dateLabel: string;
  /**
   * Used for sorting events chronologically.
   */
  startDate: string;
  /**
   * Which country site this was authored on. Leave empty for the main amintl.org site.
   */
  tenant?: (number | null) | Tenant;
  /**
   * Show on every country site's feed, in addition to its home site.
   */
  shareWithAllTenants?: boolean | null;
  /**
   * Also show on these specific country sites.
   */
  shareWithTenants?: (number | Tenant)[] | null;
  /**
   * Also show on the main amintl.org feed (only relevant when this was authored on a country site).
   */
  shareWithMainSite?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL segment, e.g. "spring-retreat-recap" for /news/spring-retreat-recap
   */
  slug: string;
  category: 'news' | 'editorial' | 'photo-news' | 'testimony';
  publishedDate: string;
  coverImage?: (number | null) | Media;
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Which country site this was authored on. Leave empty for the main amintl.org site.
   */
  tenant?: (number | null) | Tenant;
  /**
   * Show on every country site's feed, in addition to its home site.
   */
  shareWithAllTenants?: boolean | null;
  /**
   * Also show on these specific country sites.
   */
  shareWithTenants?: (number | Tenant)[] | null;
  /**
   * Also show on the main amintl.org feed (only relevant when this was authored on a country site).
   */
  shareWithMainSite?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries".
 */
export interface Ministry {
  id: number;
  /**
   * Short label shown on the card, e.g. "Connect", "Grow".
   */
  tag: string;
  title: string;
  description: string;
  href?: string | null;
  image?: (number | null) | Media;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bible-study-signups".
 */
export interface BibleStudySignup {
  id: number;
  firstName: string;
  lastName: string;
  age: 'Under 18' | '18–22' | '23–27' | '28–34' | '35+';
  maritalStatus: 'Single' | 'Engaged' | 'Married' | 'Divorced' | 'Widowed';
  schoolName?: string | null;
  graduationYear?: string | null;
  preferredTimes: string;
  email: string;
  phone: string;
  testimony: string;
  whyStudyBible: string;
  howDidYouHear: 'Friend or classmate' | 'Social media' | 'Campus event' | 'Church' | 'AM Academy' | 'Other';
  comments?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-applications".
 */
export interface VolunteerApplication {
  id: number;
  fullName: string;
  address: string;
  city: string;
  stateProvince: string;
  country: string;
  zipCode: string;
  telephone: string;
  email: string;
  availability: string;
  whyVolunteer: string;
  testimony: string;
  giftsAndTalents: string;
  churchOrgName: string;
  q1Convicted: 'Yes' | 'No';
  q1Explanation?: string | null;
  q2SexualOffense: 'Yes' | 'No';
  q2Explanation?: string | null;
  q3ReportedAgency: 'Yes' | 'No';
  q3Explanation?: string | null;
  q4ChurchDiscipline: 'Yes' | 'No';
  q4Explanation?: string | null;
  q5DismissedEmployment: 'Yes' | 'No';
  q5Explanation?: string | null;
  q6Investigation: 'Yes' | 'No';
  q6Explanation?: string | null;
  signature: string;
  signatureDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Change wording for one country site. Anything not listed here keeps following the main amintl.org copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-content".
 */
export interface TenantContent {
  id: number;
  /**
   * Set automatically from the country and language below.
   */
  label?: string | null;
  /**
   * The country site these changes apply to.
   */
  tenant: number | Tenant;
  /**
   * Leave empty to apply to this country in every language — the usual choice. Set a language only when a country reads the site in more than one and the wording should differ between them.
   */
  locale?:
    | (
        | 'en'
        | 'es'
        | 'fr'
        | 'de'
        | 'pt'
        | 'ko'
        | 'ja'
        | 'zh'
        | 'it'
        | 'ru'
        | 'tr'
        | 'id'
        | 'nl'
        | 'pl'
        | 'uk'
        | 'cs'
        | 'sk'
        | 'el'
        | 'hu'
        | 'ro'
        | 'sv'
        | 'ar'
        | 'he'
        | 'ur'
        | 'hi'
        | 'bn'
        | 'ta'
        | 'ne'
        | 'si'
        | 'my'
        | 'th'
        | 'vi'
        | 'fil'
        | 'ms'
        | 'mn'
        | 'kk'
        | 'sw'
        | 'am'
        | 'af'
        | 'zu'
        | 'xh'
        | 'rw'
        | 'rn'
        | 'mg'
        | 'ht'
        | 'fj'
        | 'hif'
        | 'rm'
      )
    | null;
  /**
   * Pick the piece of copy to change, then write this country's version. The main version is shown next to each option.
   */
  overrides?:
    | {
        /**
         * Searchable by what the text says, not just its name — type a few words of the sentence you want to change.
         */
        key:
          | 'AboutPage.blockquote'
          | 'AboutPage.breadcrumb'
          | 'AboutPage.cardMissionStatementTitle'
          | 'AboutPage.cardStatementOfFaithTitle'
          | 'AboutPage.heroTitle'
          | 'AboutPage.or'
          | 'AboutPage.paragraph1'
          | 'AboutPage.paragraph2'
          | 'AboutPage.paragraph2Prefix'
          | 'AboutPage.paragraph3'
          | 'AboutPage.paragraph4'
          | 'AboutPage.paragraph5'
          | 'AboutPage.readStatementOfFaith'
          | 'AboutPage.traceHistory'
          | 'AboutSubNav.history'
          | 'AboutSubNav.leadership'
          | 'AboutSubNav.membership'
          | 'AboutSubNav.missionStatement'
          | 'AboutSubNav.ourFirstChairman'
          | 'AboutSubNav.statementOfFaith'
          | 'AboutSubNav.whoWeAre'
          | 'AnnouncementBar.amAcademy'
          | 'AnnouncementBar.tagline'
          | 'Common.clickHere'
          | 'Common.home'
          | 'Common.learnMore'
          | 'Common.readMore'
          | 'Common.tagline'
          | 'CountrySwitcher.international'
          | 'CountrySwitcher.label'
          | 'Footer.aboutAM'
          | 'Footer.amAcademy'
          | 'Footer.bibleStudyProgram'
          | 'Footer.chapterAffiliation'
          | 'Footer.connectGrowLeadSent'
          | 'Footer.contact'
          | 'Footer.contactUs'
          | 'Footer.copyright'
          | 'Footer.email'
          | 'Footer.events'
          | 'Footer.fourSpiritualThemes'
          | 'Footer.getInvolved'
          | 'Footer.give'
          | 'Footer.leadership'
          | 'Footer.legacyOfChairman'
          | 'Footer.media'
          | 'Footer.missionStatement'
          | 'Footer.news'
          | 'Footer.orgLocation'
          | 'Footer.orgName'
          | 'Footer.ourHistory'
          | 'Footer.ourMinistries'
          | 'Footer.ourNetwork'
          | 'Footer.statementOfFaith'
          | 'Footer.tagline'
          | 'Footer.whatWeDo'
          | 'Footer.whoWeAre'
          | 'GetInvolvedHub.connectHeading'
          | 'GetInvolvedHub.connectItems'
          | 'GetInvolvedHub.connectStep1Body'
          | 'GetInvolvedHub.connectStep1Title'
          | 'GetInvolvedHub.connectStep2BodyPrefix'
          | 'GetInvolvedHub.connectStep2BodySuffix'
          | 'GetInvolvedHub.connectStep2SignUp'
          | 'GetInvolvedHub.connectStep2Title'
          | 'GetInvolvedHub.connectStep3BodyPrefix'
          | 'GetInvolvedHub.connectStep3BodySuffix'
          | 'GetInvolvedHub.connectStep3SignUp'
          | 'GetInvolvedHub.connectStep3Title'
          | 'GetInvolvedHub.connectStep4BodyPrefix'
          | 'GetInvolvedHub.connectStep4BodySuffix'
          | 'GetInvolvedHub.connectStep4ContactHere'
          | 'GetInvolvedHub.connectStep4Title'
          | 'GetInvolvedHub.connectTag'
          | 'GetInvolvedHub.fruitfulBody'
          | 'GetInvolvedHub.fruitfulTitle'
          | 'GetInvolvedHub.growHeading'
          | 'GetInvolvedHub.growIntro'
          | 'GetInvolvedHub.growItems'
          | 'GetInvolvedHub.growTag'
          | 'GetInvolvedHub.leadHeading'
          | 'GetInvolvedHub.leadItems'
          | 'GetInvolvedHub.leadStep1Body'
          | 'GetInvolvedHub.leadStep1Title'
          | 'GetInvolvedHub.leadStep2Body'
          | 'GetInvolvedHub.leadStep2Title'
          | 'GetInvolvedHub.leadStep3Body'
          | 'GetInvolvedHub.leadStep3Title'
          | 'GetInvolvedHub.leadStep4Body'
          | 'GetInvolvedHub.leadStep4Title'
          | 'GetInvolvedHub.leadTag'
          | 'GetInvolvedHub.matureBody'
          | 'GetInvolvedHub.matureTitle'
          | 'GetInvolvedHub.navigatingBody'
          | 'GetInvolvedHub.navigatingTitle'
          | 'GetInvolvedHub.nextStepsBody'
          | 'GetInvolvedHub.nextStepsTitle'
          | 'GetInvolvedHub.rebornBody'
          | 'GetInvolvedHub.rebornTitle'
          | 'GetInvolvedHub.roadmapEyebrow'
          | 'GetInvolvedHub.roadmapHeading'
          | 'GetInvolvedHub.roadmapHeroTitle'
          | 'GetInvolvedHub.sentHeading'
          | 'GetInvolvedHub.sentItems'
          | 'GetInvolvedHub.sentLinkAlumniConnect'
          | 'GetInvolvedHub.sentLinkBibleTeachers'
          | 'GetInvolvedHub.sentLinkMissionaries'
          | 'GetInvolvedHub.sentLinkStaff'
          | 'GetInvolvedHub.sentParagraph1'
          | 'GetInvolvedHub.sentParagraph2'
          | 'GetInvolvedHub.sentParagraph3'
          | 'GetInvolvedHub.sentTag'
          | 'GetInvolvedSubNav.alumniConnect'
          | 'GetInvolvedSubNav.bibleStudies'
          | 'GetInvolvedSubNav.bibleTeacherTraining'
          | 'GetInvolvedSubNav.chapterStaff'
          | 'GetInvolvedSubNav.donate'
          | 'GetInvolvedSubNav.groupActivities'
          | 'GetInvolvedSubNav.internship'
          | 'GetInvolvedSubNav.onlineBibleStudy'
          | 'GetInvolvedSubNav.volunteer'
          | 'Header.connect'
          | 'Header.contactUs'
          | 'Header.getInvolved'
          | 'Header.getInvolvedMenu.bibleStudies'
          | 'Header.getInvolvedMenu.bibleTeacherTraining'
          | 'Header.getInvolvedMenu.chapterAffiliation'
          | 'Header.getInvolvedMenu.donate'
          | 'Header.getInvolvedMenu.groupActivities'
          | 'Header.getInvolvedMenu.internship'
          | 'Header.getInvolvedMenu.onlineBibleStudy'
          | 'Header.getInvolvedMenu.volunteer'
          | 'Header.give'
          | 'Header.groups.aboutAm.description'
          | 'Header.groups.aboutAm.title'
          | 'Header.groups.bibleStudy.description'
          | 'Header.groups.bibleStudy.title'
          | 'Header.groups.events.description'
          | 'Header.groups.events.title'
          | 'Header.groups.getInvolved.description'
          | 'Header.groups.getInvolved.title'
          | 'Header.groups.latestNews.description'
          | 'Header.groups.latestNews.title'
          | 'Header.groups.leadership.description'
          | 'Header.groups.leadership.title'
          | 'Header.groups.supportMission.description'
          | 'Header.groups.supportMission.title'
          | 'Header.groups.whatWeDo.description'
          | 'Header.groups.whatWeDo.title'
          | 'Header.megaMenu.aboutHeading'
          | 'Header.megaMenu.allArticles'
          | 'Header.megaMenu.ctaBibleStudy'
          | 'Header.megaMenu.ctaFindChapter'
          | 'Header.megaMenu.ctaGive'
          | 'Header.megaMenu.featuredHeading'
          | 'Header.megaMenu.whatWeDoHeading'
          | 'Header.mobile.back'
          | 'Header.mobile.close'
          | 'Header.mobile.menu'
          | 'Header.news'
          | 'Header.newsMenu.editorial'
          | 'Header.newsMenu.events'
          | 'Header.newsMenu.featured'
          | 'Header.newsMenu.photoNews'
          | 'Header.newsMenu.testimony'
          | 'Header.ourNetwork'
          | 'Header.toggleNav'
          | 'Header.whatWeDo'
          | 'Header.whatWeDoMenu.administration'
          | 'Header.whatWeDoMenu.amAcademy'
          | 'Header.whatWeDoMenu.bibleStudyProgram'
          | 'Header.whatWeDoMenu.fourSpiritualThemes'
          | 'Header.whatWeDoMenu.ourMinistries'
          | 'Header.whatWeDoMenu.pillarsOfMission'
          | 'Header.whoWeAre'
          | 'Header.whoWeAreMenu.history'
          | 'Header.whoWeAreMenu.membership'
          | 'Header.whoWeAreMenu.ourFirstChairmen'
          | 'Header.whoWeAreMenu.ourLeadership'
          | 'Header.whoWeAreMenu.ourMission'
          | 'Header.whoWeAreMenu.statementOfFaith'
          | 'Header.whoWeAreMenu.whoWeAre'
          | 'Home.BibleStudyProgram.cta'
          | 'Home.BibleStudyProgram.description'
          | 'Home.BibleStudyProgram.eyebrow'
          | 'Home.BibleStudyProgram.heading'
          | 'Home.Events.allEvents'
          | 'Home.Events.event1Date'
          | 'Home.Events.event1Title'
          | 'Home.Events.event2Date'
          | 'Home.Events.event2Title'
          | 'Home.Events.event3Date'
          | 'Home.Events.event3Title'
          | 'Home.Events.eyebrow'
          | 'Home.Events.heading'
          | 'Home.GetInvolved.bibleStudies'
          | 'Home.GetInvolved.eyebrow'
          | 'Home.GetInvolved.heading'
          | 'Home.GetInvolved.internship'
          | 'Home.GetInvolved.volunteer'
          | 'Home.Hero.dragToExplore'
          | 'Home.Hero.eyebrow'
          | 'Home.Hero.headingLine1'
          | 'Home.Hero.headingWeAre'
          | 'Home.Hero.headingWhere'
          | 'Home.Hero.joinBibleStudy'
          | 'Home.Hero.stat1Label'
          | 'Home.Hero.stat1Value'
          | 'Home.Hero.stat2Label'
          | 'Home.Hero.stat2Value'
          | 'Home.Hero.stat3Label'
          | 'Home.Hero.stat3Value'
          | 'Home.Hero.whoWeAre'
          | 'Home.HonoraryChairman.eyebrow'
          | 'Home.HonoraryChairman.followingLegacy'
          | 'Home.HonoraryChairman.name'
          | 'Home.HonoraryChairman.quoteLine1'
          | 'Home.HonoraryChairman.quoteLine2'
          | 'Home.HonoraryChairman.quoteLine3'
          | 'Home.HonoraryChairman.quoteReference'
          | 'Home.Media.eyebrow'
          | 'Home.Media.heading'
          | 'Home.Media.moreContents'
          | 'Home.Media.playVideo'
          | 'Home.Media.post1Date'
          | 'Home.Media.post1Title'
          | 'Home.Media.post2Date'
          | 'Home.Media.post2Title'
          | 'Home.Media.post3Date'
          | 'Home.Media.post3Title'
          | 'Home.Media.post4Date'
          | 'Home.Media.post4Title'
          | 'Home.Ministries.connectDescription'
          | 'Home.Ministries.connectTag'
          | 'Home.Ministries.connectTitle'
          | 'Home.Ministries.eyebrow'
          | 'Home.Ministries.getInvolved'
          | 'Home.Ministries.growDescription'
          | 'Home.Ministries.growTag'
          | 'Home.Ministries.growTitle'
          | 'Home.Ministries.heading'
          | 'Home.Ministries.leadDescription'
          | 'Home.Ministries.leadTag'
          | 'Home.Ministries.leadTitle'
          | 'Home.Ministries.learnMore'
          | 'Home.Ministries.sentDescription'
          | 'Home.Ministries.sentTag'
          | 'Home.Ministries.sentTitle'
          | 'Home.Newsletter.cta'
          | 'Home.Newsletter.description'
          | 'Home.Newsletter.heading'
          | 'Home.OurMission.eyebrow'
          | 'Home.OurMission.history'
          | 'Home.OurMission.nameOrigin'
          | 'Home.OurMission.ourHistory'
          | 'Home.OurMission.readFullStatement'
          | 'Home.OurMission.statementEmphasis'
          | 'Home.OurMission.statementPrefix'
          | 'Home.OurMission.statementSuffix'
          | 'Home.OurNetwork.description'
          | 'Home.OurNetwork.eyebrow'
          | 'Home.OurNetwork.heading'
          | 'Home.OurNetwork.noMatches'
          | 'Home.OurNetwork.searchPlaceholder'
          | 'Home.OurNetwork.startChapter'
          | 'Home.PartnerWithUs.description'
          | 'Home.PartnerWithUs.eyebrow'
          | 'Home.PartnerWithUs.giveToday'
          | 'Home.PartnerWithUs.heading'
          | 'Home.PartnerWithUs.talkToUs'
          | 'Home.QuickLinks.findCampusDescription'
          | 'Home.QuickLinks.findCampusTitle'
          | 'Home.QuickLinks.getInvolvedDescription'
          | 'Home.QuickLinks.getInvolvedTitle'
          | 'Home.QuickLinks.joinBibleStudyDescription'
          | 'Home.QuickLinks.joinBibleStudyTitle'
          | 'Home.QuickLinks.supportDescription'
          | 'Home.QuickLinks.supportTitle'
          | 'InPractice.bibleStudyDescription'
          | 'InPractice.bibleStudyTag'
          | 'InPractice.eyebrow'
          | 'InPractice.heading'
          | 'InPractice.internshipsTripsDescription'
          | 'InPractice.internshipsTripsTag'
          | 'InPractice.leadershipTrainingDescription'
          | 'InPractice.leadershipTrainingTag'
          | 'InPractice.onlineEducationDescription'
          | 'InPractice.onlineEducationTag'
          | 'LanguageSwitcher.label'
          | 'Logo.international'
          | 'Network.breadcrumb'
          | 'Network.chaptersHeading'
          | 'Network.chaptersSoon'
          | 'Network.communityEyebrow'
          | 'Network.continentSubtitle'
          | 'Network.countriesEyebrow'
          | 'Network.countriesHeading'
          | 'Network.countriesSubheading'
          | 'Network.exploreEyebrow'
          | 'Network.heading'
          | 'Network.joinChapter'
          | 'Network.map.captionEastCentralAsia'
          | 'Network.map.captionSouthAsia'
          | 'Network.map.captionSoutheastAsia'
          | 'Network.map.clear'
          | 'Network.map.hqBadge'
          | 'Network.map.loading'
          | 'Network.map.regionalHqBadge'
          | 'Network.map.regionAria'
          | 'Network.map.regionHint'
          | 'Network.map.world'
          | 'Network.map.worldAria'
          | 'Network.map.worldHint'
          | 'Network.map.zoomIn'
          | 'Network.noSitesBodyPrefix'
          | 'Network.noSitesBodySuffix'
          | 'Network.noSitesLink'
          | 'Network.noSitesTitle'
          | 'Network.partnerWithUs'
          | 'Network.regions.africa'
          | 'Network.regions.asia'
          | 'Network.regions.europe'
          | 'Network.regions.northamerica'
          | 'Network.regions.oceania'
          | 'Network.regions.southamerica'
          | 'Network.regionsHeading'
          | 'Network.regionsSubheading'
          | 'Network.siteCount'
          | 'Network.visitSite'
          | 'NewsSubNav.editorial'
          | 'NewsSubNav.events'
          | 'NewsSubNav.featuredNews'
          | 'NewsSubNav.photoNews'
          | 'NewsSubNav.testimony'
          | 'WhatWeDoSubNav.administration'
          | 'WhatWeDoSubNav.pillarsOfMission';
        /**
         * This country's wording. For the roadmap bullet lists, put one item per line.
         */
        value: string;
        /**
         * The main amintl.org copy this replaces, for reference.
         */
        mainVersion?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Add, edit, or remove pages without a code deploy. Pages with no tenant belong to the main amintl.org site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path segment(s), e.g. "our-story" or "programs/summer-camp". Leave empty only for a home page.
   */
  slug?: string | null;
  /**
   * Leave empty for a page on the main amintl.org site.
   */
  tenant?: (number | null) | Tenant;
  /**
   * This is the home page — served at / for the main site, or /{continent}/{country} for a tenant.
   */
  isHome?: boolean | null;
  published?: boolean | null;
  /**
   * Label to show in site navigation. Leave empty to keep this page out of the nav.
   */
  navLabel?: string | null;
  hero?: {
    heading?: string | null;
    subheading?: string | null;
    image?: (number | null) | Media;
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Homepage-style content sections (used instead of the simple hero/body above — mainly for a site's home page).
   */
  sections?:
    | (
        | {
            eyebrow?: string | null;
            headingLine1: string;
            headingHighlight1: string;
            headingHighlight2: string;
            joinBibleStudyLabel: string;
            whoWeAreLabel: string;
            backgroundImage?: (number | null) | Media;
            stat1: {
              value: string;
              label: string;
            };
            stat2: {
              value: string;
              label: string;
            };
            stat3: {
              value: string;
              label: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description: string;
            ctaLabel: string;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bibleStudyProgram';
          }
        | {
            links?:
              | {
                  icon: 'book' | 'pin' | 'people' | 'heart';
                  title: string;
                  description: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quickLinks';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            getInvolvedLabel: string;
            steps?:
              | {
                  tag: string;
                  title: string;
                  description: string;
                  href: string;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ministries';
          }
        | {
            eyebrow?: string | null;
            statementPrefix: string;
            statementEmphasis: string;
            statementSuffix: string;
            readFullStatementLabel: string;
            nameOrigin: string;
            history: string;
            ourHistoryLabel: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ourMission';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            cards?:
              | {
                  title: string;
                  href: string;
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'getInvolved';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            moreContentsLabel: string;
            playVideoLabel: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            allEventsLabel: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'events';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description: string;
            startChapterLabel: string;
            searchPlaceholder: string;
            noMatchesLabel: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ourNetwork';
          }
        | {
            eyebrow?: string | null;
            followingLegacy: string;
            name: string;
            quoteLine1: string;
            quoteLine2: string;
            quoteLine3: string;
            quoteReference: string;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'honoraryChairman';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description: string;
            giveTodayLabel: string;
            talkToUsLabel: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnerWithUs';
          }
        | {
            heading: string;
            description: string;
            ctaLabel: string;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  subject: string;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-intents".
 */
export interface DonationIntent {
  id: number;
  fullName: string;
  email: string;
  amount: number;
  frequency: 'One-Time' | 'Monthly' | 'Yearly';
  status: 'pending' | 'completed' | 'failed';
  stripeSessionId?: string | null;
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  stripePaymentIntentId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * Chapter or partner organization name.
   */
  name: string;
  contactName?: string | null;
  contactEmail: string;
  type?: ('chapter' | 'partner-org' | 'other') | null;
  notes?: string | null;
  stripeCustomerId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  partner: number | Partner;
  /**
   * Shown to the partner on the invoice.
   */
  memo?: string | null;
  lineItems: {
    description: string;
    /**
     * Dollars.
     */
    amount: number;
    id?: string | null;
  }[];
  dueDate?: string | null;
  status?: ('draft' | 'open' | 'paid' | 'void' | 'uncollectible') | null;
  /**
   * Dollars.
   */
  amountDue?: number | null;
  /**
   * Dollars.
   */
  amountPaid?: number | null;
  stripeInvoiceId?: string | null;
  stripeCustomerId?: string | null;
  hostedInvoiceUrl?: string | null;
  invoicePdf?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapter-affiliations".
 */
export interface ChapterAffiliation {
  id: number;
  applicationType: 'Annual reaffirmation' | 'New chapter';
  city: string;
  country: string;
  targetUniversity: string;
  startDate: string;
  memberCount: string;
  chartered: 'Yes' | 'No';
  charterLetter?: (number | null) | Media;
  constitutionFile?: (number | null) | Media;
  delayReason?: string | null;
  leaderName: string;
  leaderRole: string;
  leaderEmail: string;
  leaderPhone: string;
  additionalLeaders?:
    | {
        name?: string | null;
        role?: string | null;
        email?: string | null;
        phone?: string | null;
        id?: string | null;
      }[]
    | null;
  leadershipChanges?: string | null;
  attestation: boolean;
  memberListFile?: (number | null) | Media;
  members?:
    | {
        name?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-applications".
 */
export interface MembershipApplication {
  id: number;
  fullName: string;
  phone: string;
  email: string;
  chapter: string;
  membershipTier: 'Newcomer' | 'Registered' | 'Volunteer' | 'Staff' | 'Leader';
  statementOfFaithAgreement?: 'I agree and share the AM Statement of Faith' | null;
  message?: string | null;
  attestation: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'campuses';
        value: number | Campus;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'ministries';
        value: number | Ministry;
      } | null)
    | ({
        relationTo: 'bible-study-signups';
        value: number | BibleStudySignup;
      } | null)
    | ({
        relationTo: 'volunteer-applications';
        value: number | VolunteerApplication;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'tenant-content';
        value: number | TenantContent;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'donation-intents';
        value: number | DonationIntent;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'chapter-affiliations';
        value: number | ChapterAffiliation;
      } | null)
    | ({
        relationTo: 'membership-applications';
        value: number | MembershipApplication;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campuses_select".
 */
export interface CampusesSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  active?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverImage?: T;
  location?: T;
  excerpt?: T;
  dateLabel?: T;
  startDate?: T;
  tenant?: T;
  shareWithAllTenants?: T;
  shareWithTenants?: T;
  shareWithMainSite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedDate?: T;
  coverImage?: T;
  excerpt?: T;
  body?: T;
  tenant?: T;
  shareWithAllTenants?: T;
  shareWithTenants?: T;
  shareWithMainSite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries_select".
 */
export interface MinistriesSelect<T extends boolean = true> {
  tag?: T;
  title?: T;
  description?: T;
  href?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bible-study-signups_select".
 */
export interface BibleStudySignupsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  age?: T;
  maritalStatus?: T;
  schoolName?: T;
  graduationYear?: T;
  preferredTimes?: T;
  email?: T;
  phone?: T;
  testimony?: T;
  whyStudyBible?: T;
  howDidYouHear?: T;
  comments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-applications_select".
 */
export interface VolunteerApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  address?: T;
  city?: T;
  stateProvince?: T;
  country?: T;
  zipCode?: T;
  telephone?: T;
  email?: T;
  availability?: T;
  whyVolunteer?: T;
  testimony?: T;
  giftsAndTalents?: T;
  churchOrgName?: T;
  q1Convicted?: T;
  q1Explanation?: T;
  q2SexualOffense?: T;
  q2Explanation?: T;
  q3ReportedAgency?: T;
  q3Explanation?: T;
  q4ChurchDiscipline?: T;
  q4Explanation?: T;
  q5DismissedEmployment?: T;
  q5Explanation?: T;
  q6Investigation?: T;
  q6Explanation?: T;
  signature?: T;
  signatureDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  country?: T;
  city?: T;
  continent?: T;
  slug?: T;
  locale?: T;
  countryCodes?: T;
  languages?: T;
  tier?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-content_select".
 */
export interface TenantContentSelect<T extends boolean = true> {
  label?: T;
  tenant?: T;
  locale?: T;
  overrides?:
    | T
    | {
        key?: T;
        value?: T;
        mainVersion?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tenant?: T;
  isHome?: T;
  published?: T;
  navLabel?: T;
  hero?:
    | T
    | {
        heading?: T;
        subheading?: T;
        image?: T;
      };
  body?: T;
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headingLine1?: T;
              headingHighlight1?: T;
              headingHighlight2?: T;
              joinBibleStudyLabel?: T;
              whoWeAreLabel?: T;
              backgroundImage?: T;
              stat1?:
                | T
                | {
                    value?: T;
                    label?: T;
                  };
              stat2?:
                | T
                | {
                    value?: T;
                    label?: T;
                  };
              stat3?:
                | T
                | {
                    value?: T;
                    label?: T;
                  };
              id?: T;
              blockName?: T;
            };
        bibleStudyProgram?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              ctaLabel?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        quickLinks?:
          | T
          | {
              links?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ministries?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              getInvolvedLabel?: T;
              steps?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    description?: T;
                    href?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ourMission?:
          | T
          | {
              eyebrow?: T;
              statementPrefix?: T;
              statementEmphasis?: T;
              statementSuffix?: T;
              readFullStatementLabel?: T;
              nameOrigin?: T;
              history?: T;
              ourHistoryLabel?: T;
              id?: T;
              blockName?: T;
            };
        getInvolved?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    href?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              moreContentsLabel?: T;
              playVideoLabel?: T;
              id?: T;
              blockName?: T;
            };
        events?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              allEventsLabel?: T;
              id?: T;
              blockName?: T;
            };
        ourNetwork?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              startChapterLabel?: T;
              searchPlaceholder?: T;
              noMatchesLabel?: T;
              id?: T;
              blockName?: T;
            };
        honoraryChairman?:
          | T
          | {
              eyebrow?: T;
              followingLegacy?: T;
              name?: T;
              quoteLine1?: T;
              quoteLine2?: T;
              quoteLine3?: T;
              quoteReference?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        partnerWithUs?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              giveTodayLabel?: T;
              talkToUsLabel?: T;
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              heading?: T;
              description?: T;
              ctaLabel?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-intents_select".
 */
export interface DonationIntentsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  amount?: T;
  frequency?: T;
  status?: T;
  stripeSessionId?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  stripePaymentIntentId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  contactName?: T;
  contactEmail?: T;
  type?: T;
  notes?: T;
  stripeCustomerId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  partner?: T;
  memo?: T;
  lineItems?:
    | T
    | {
        description?: T;
        amount?: T;
        id?: T;
      };
  dueDate?: T;
  status?: T;
  amountDue?: T;
  amountPaid?: T;
  stripeInvoiceId?: T;
  stripeCustomerId?: T;
  hostedInvoiceUrl?: T;
  invoicePdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapter-affiliations_select".
 */
export interface ChapterAffiliationsSelect<T extends boolean = true> {
  applicationType?: T;
  city?: T;
  country?: T;
  targetUniversity?: T;
  startDate?: T;
  memberCount?: T;
  chartered?: T;
  charterLetter?: T;
  constitutionFile?: T;
  delayReason?: T;
  leaderName?: T;
  leaderRole?: T;
  leaderEmail?: T;
  leaderPhone?: T;
  additionalLeaders?:
    | T
    | {
        name?: T;
        role?: T;
        email?: T;
        phone?: T;
        id?: T;
      };
  leadershipChanges?: T;
  attestation?: T;
  memberListFile?: T;
  members?:
    | T
    | {
        name?: T;
        email?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-applications_select".
 */
export interface MembershipApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  email?: T;
  chapter?: T;
  membershipTier?: T;
  statementOfFaithAgreement?: T;
  message?: T;
  attestation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}