// GENERATED by scripts/generate-map-views.mjs — do not edit by hand.
import type { MapView, MapViewKey } from "./types";
export type { MapView, MapViewKey };
export { default as worldView } from "./world";

export const MAP_VIEW_LOADERS: Record<MapViewKey, () => Promise<MapView>> = {
  world: () => import("./world").then((m) => m.default),
  northamerica: () => import("./northamerica").then((m) => m.default),
  southamerica: () => import("./southamerica").then((m) => m.default),
  europe: () => import("./europe").then((m) => m.default),
  africa: () => import("./africa").then((m) => m.default),
  asia: () => import("./asia").then((m) => m.default),
  oceania: () => import("./oceania").then((m) => m.default),
};
