// GENERATED by scripts/generate-map-views.mjs — do not edit by hand.
export type MapView = {
  viewBox: readonly [number, number, number, number];
  rotate: number;
  scale: number;
  translate: readonly [number, number];
  land: string;
  borders: string;
  subdivisions?: string;
};
export type MapViewKey = "world" | "northamerica" | "southamerica" | "europe" | "africa" | "asia" | "oceania";
